In [1]:
from bs4 import BeautifulSoup
import requests
url  = BeautifulSoup('https://www.worldometers.info/coronavirus/','html.parser')
soup = requests.get(url)
soup

C:\Users\user\anaconda3\lib\site-packages\bs4\__init__.py:404: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  warnings.warn(

In [2]:
codes = BeautifulSoup(soup.text,"lxml")
codes

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]--><!--[if IE 9]> <html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>COVID Live - Coronavirus Statistics - Worldometer</title>
<meta content="Live statistics and coronavirus news tracking the number of confirmed cases, recovered patients, tests, and death toll due to the COVID-19 coronavirus from Wuhan, China. Coronavirus counter with new cases, deaths, and number of tests per 1 Million population. Historical data and info. Daily charts, graphs, news and updates" name="description"/>
<!-- Favicon -->
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- og image -->
<meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/>
<!-- Bootstrap -->
<link href="/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/wm16.css" rel="stylesheet"/>
<!-- font awesome -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<script src="/js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/js/ie10-viewport-bug-workaround.js"></script>
<!-- tables
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js"></script>
 -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example2').dataTable( {
        "scrollCollapse": true,
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#table3').dataTable( {
        "scrollCollapse": true,
				 "order": [[ 1, 'desc' ]],
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example').dataTable( {
        "scrollCollapse": true,
		"searching": false,

		"sDom": '<"top">rt<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
$(document).ready(function() {
	$('#popbycountry').dataTable();
} );
	</script>
<!-- FREESTAR -->
<script data-cfasync="false" type="text/javascript">
  var freestar = freestar || {};
  freestar.hitTime = Date.now();
  freestar.queue = freestar.queue || [];
  freestar.config = freestar.config || {};
  freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true;
  freestar.config.enabled_slots = [];
  !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document);
</script>
</head>
<body>
<!-- Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<!--
<script type="text/javascript" async=true>
(function() {
  var host = 'worldometers.info';
  var element = document.createElement('script');
  var firstScript = document.getElementsByTagName('script')[0];
  var url = 'https://quantcast.mgr.consensu.org'
    .concat('/choice/', 'Pd9JxUkvV0m7q', '/', host, '/choice.js');
  var uspTries = 0;
  var uspTriesLimit = 3;
  element.async = true;
  element.type = 'text/javascript';
  element.src = url;

  firstScript.parentNode.insertBefore(element, firstScript);

  function makeStub() {
    var TCF_LOCATOR_NAME = '__tcfapiLocator';
    var queue = [];
    var win = window;
    var cmpFrame;

    function addFrame() {
      var doc = win.document;
      var otherCMP = !!(win.frames[TCF_LOCATOR_NAME]);

      if (!otherCMP) {
        if (doc.body) {
          var iframe = doc.createElement('iframe');

          iframe.style.cssText = 'display:none';
          iframe.name = TCF_LOCATOR_NAME;
          doc.body.appendChild(iframe);
        } else {
          setTimeout(addFrame, 5);
        }
      }
      return !otherCMP;
    }

    function tcfAPIHandler() {
      var gdprApplies;
      var args = arguments;

      if (!args.length) {
        return queue;
      } else if (args[0] === 'setGdprApplies') {
        if (
          args.length > 3 &&
          args[2] === 2 &&
          typeof args[3] === 'boolean'
        ) {
          gdprApplies = args[3];
          if (typeof args[2] === 'function') {
            args[2]('set', true);
          }
        }
      } else if (args[0] === 'ping') {
        var retr = {
          gdprApplies: gdprApplies,
          cmpLoaded: false,
          cmpStatus: 'stub'
        };

        if (typeof args[2] === 'function') {
          args[2](retr);
        }
      } else {
        queue.push(args);
      }
    }

    function postMessageEventHandler(event) {
      var msgIsString = typeof event.data === 'string';
      var json = {};

      try {
        if (msgIsString) {
          json = JSON.parse(event.data);
        } else {
          json = event.data;
        }
      } catch (ignore) {}

      var payload = json.__tcfapiCall;

      if (payload) {
        window.__tcfapi(
          payload.command,
          payload.version,
          function(retValue, success) {
            var returnMsg = {
              __tcfapiReturn: {
                returnValue: retValue,
                success: success,
                callId: payload.callId
              }
            };
            if (msgIsString) {
              returnMsg = JSON.stringify(returnMsg);
            }
            event.source.postMessage(returnMsg, '*');
          },
          payload.parameter
        );
      }
    }

    while (win) {
      try {
        if (win.frames[TCF_LOCATOR_NAME]) {
          cmpFrame = win;
          break;
        }
      } catch (ignore) {}

      if (win === window.top) {
        break;
      }
      win = win.parent;
    }
    if (!cmpFrame) {
      addFrame();
      win.__tcfapi = tcfAPIHandler;
      win.addEventListener('message', postMessageEventHandler, false);
    }
  };

  makeStub();

  var uspStubFunction = function() {
    var arg = arguments;
    if (typeof window.__uspapi !== uspStubFunction) {
      setTimeout(function() {
        if (typeof window.__uspapi !== 'undefined') {
          window.__uspapi.apply(window.__uspapi, arg);
        }
      }, 500);
    }
  };

  var checkIfUspIsReady = function() {
    uspTries++;
    if (window.__uspapi === uspStubFunction && uspTries < uspTriesLimit) {
      console.warn('USP is not accessible');
    } else {
      clearInterval(uspInterval);
    }
  };

  if (typeof window.__uspapi === 'undefined') {
    window.__uspapi = uspStubFunction;
    var uspInterval = setInterval(checkIfUspIsReady, 6000);
  }
})();
</script>
-->
<!-- End Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1438574-2', 'auto');
  ga('send', 'pageview');
</script>
<!-- GA wm old (info) -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1438574-30');
</script>
<!-- GDPR consent -->
<link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "href": "http://www.worldometers.info/policy/"
  }
})});
</script>
<style type="text/css">
    .style1 {
        color: #666666
    }
</style>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<div class="logo"><a class="navbar-brand" href="/"><img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/></a></div>
<button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="navbar-collapse collapse" id="navbar-main">
<ul class="nav navbar-nav">
<li><a href="/coronavirus/">Coronavirus</a></li>
<li><a href="/population/">Population</a></li>
</ul>
</div>
</div>
</div>
<!-- MAIN -->
<div class="container">
<!-- TOP AD -->
<div class="row">
<div style="text-align:left; margin-bottom:10px">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- wm_top970 -->
<ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
<!-- TOP AD -->
<!-- MAIN  -->
<!-- CENTER -->
<div class="row"> <div class="col-md-8">
<!-- *** CONTENT A *** -->
<div class="content-inner">
<style>
    .number-table {
        font-size: 20px;
        font-weight: bold
    }

    .number-table-main {
        font-size: 24px;
        font-weight: bold
    }
</style>
<!-- charts -->
<script src="/js/highcharts.js"></script>
<style type="text/css">
    .source {}

    .style2 {
        color: #FF0000
    }

    .style4 {
        color: #FF0000;
        font-weight: bold;
    }

    .style6 {
        font-size: 12px;
        color: #bbb;
        font-weight: bold;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source11 {
        font-size: 12px;
        color: #bbb;
    }

    .source111 {}

    .source1111 {
        font-size: 12px;
        color: #bbb;
    }


    .new_badge {

        position: absolute;
        font-size: 12px;
        top: -5px;
        right: -26px;
        background-color: #8ACA2B;
        color: white;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }

    .new_badge_link {

        background-color: #8ACA2B;
        color: white !important;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }
</style>
<div class="label-counter" id="page-top">COVID-19 Coronavirus Pandemic</div>
<div style="font-size:13px; color:#999; margin-top:5px; text-align:center">Last updated: January 08, 2023, 10:10 GMT</div>
<div style="margin-top:20px; text-align:center; font-size:14px"><a class="new_badge_link" href="/coronavirus/weekly-trends/" style="display: inline-block; position:relative;">Weekly Trends</a> - <a href="/coronavirus/worldwide-graphs/">Graphs</a> - <a href="#countries">Countries</a> - <a href="#news">News</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">668,554,883        </span>
</div>
</div>
<div style="text-align:center "><a href="#countries">view by country</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>6,713,367</span>
</div>
</div>
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>639,699,405</span>
</div>
</div>
<div style="margin-top:50px;"></div>
<!-- START -->
<style>
    .panel_flip {
        position: relative;
        height: 100%;
    }

    .panel_front {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_back {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateY(-180deg);
        -moz-transform: rotateY(-180deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_flip.flip .panel_front {

        z-index: 900;
        -webkit-transform: rotateY(180deg);
        -moz-transform: rotateY(180deg);
    }

    .panel_flip.flip .panel_back {

        z-index: 1000;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
    }

    .collapse_button {

        position: absolute;
        right: 10px;
        pointer-events: none;
        color: #70757a !important;
        height: 24px;
        width: 24px;
        line-height: 24px;
    }

    .collapse_button svg {
        display: block;
        height: 100%;
        width: 100%;
        fill: currentColor;
    }

    .rotate_180 {

        transform: rotate(180deg);
    }

    .panel_clickable {

        cursor: pointer;
    }
</style>
<script>
    var do_not_slide = false;
    $(function() {

        $('.flip_cases_front').on('click', function() {


            $(this).parent().parent().addClass('flip');
        });

        $('.flip_cases_back').on('click', function() {


            $(this).parent().parent().removeClass('flip');
        });


        $('.collapse').on('show.bs.collapse', function(el) {


            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.addClass('rotate_180');

            if (do_not_slide) {

                return;
            }

            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('show');
            } else {

                $('#panel_active').collapse('show');
            }

            do_not_slide = false;
        });

        $('.collapse').on('hide.bs.collapse', function(el) {

            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.removeClass('rotate_180');


            if (do_not_slide) {

                return;
            }


            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('hide');
            } else {

                $('#panel_active').collapse('hide');
            }

            do_not_slide = false;

        });



    });
</script>
<div class="col-md-6">
<div class="panel panel-default">
<div aria-controls="panel_active" aria-expanded="false" class="panel_clickable panel-heading" data-toggle="collapse" href="#panel_active" style="text-align:center;position:relative;">
<span class="panel-title" style="font-size:18px; text-transform:uppercase; font-weight:100">
                    Active Cases
                </span>
<span class="collapse_button"><svg focusable="false" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path>
</svg></span>
</div>
<div class="collapse" id="panel_active">
<div class="panel-body" style="text-align:center;min-height:220px;">
<div class="panel_flip">
<div class="panel_front" style="width:100%;height:100%;">
<div class="number-table-main">22,142,111</div>
<div style="font-size:13.5px">Currently Infected Patients</div>
<div style="padding-top:20px;position:relative;text-align:center; ">
<div style="float:left; text-align:center">
<span class="number-table" style="color:#8080FF">22,096,880</span> (<strong>99.8</strong>%)

                                    <div style="font-size:13px">in Mild Condition</div><br/>
</div>
<div style="float:right; text-align:center"><span class="number-table" style="color:red ">45,231</span> (<strong>0.2</strong>%)
                                    <div style="font-size:13px">Serious or Critical</div><br/>
</div>
</div>

In [3]:
codes.table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>122,004,226</td>
<td></td>
<td>1,582,327</td>
<td></td>
<td>116,661,411</td>
<td>+2,541</td>
<td>3,760,488</td>
<td>10,260</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>209,278,066</td>
<td>+260,914</td>
<td>1,516,422</td>
<td>+477</td>
<td>194,552,674</td>
<td>+109,061</td>
<td>13,208,970</td>
<td>16,218</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>243,620,216</td>
<td>+3,402</td>
<td>1,989,034</td>
<td>+51</td>
<td>238,230,364</td>
<td>+20,262</td>
<td>3,400,818</td>
<td>7,429</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>67,175,673</td>
<td></td>
<td>1,343,494</td>
<td></td>
<td>64,761,096</td>
<td>+2,549</td>
<td>1,071,083</td>
<td>10,330</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>13,730,218</td>
<td></td>
<td>23,701</td>
<td></td>
<td>13,450,170</td>
<td></td>
<td>256,347</td>
<td>157</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,745,763</td>
<td></td>
<td>258,374</td>
<td></td>
<td>12,042,984</td>
<td></td>
<td>444,405</td>
<td>837</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>668,554,883</td>
<td>+264,316</td>
<td>6,713,367</td>
<td>+528</td>
<td>639,699,405</td>
<td>+134,413</td>
<td>22,142,111</td>
<td>45,231</td>
<td>85,769</td>
<td>861.3</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">103,081,401</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,121,089                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">99,876,630</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">2,083,682</td>
<td style="font-weight: bold; text-align:right">5,077</td>
<td style="font-weight: bold; text-align:right">307,885</td>
<td style="font-weight: bold; text-align:right">3,348</td>
<td style="font-weight: bold; text-align:right">1,155,402,577</td>
<td style="font-weight: bold; text-align:right">3,450,969</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>299</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,224</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,681,017</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">530,720                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,146,781</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">3,516</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">31,765</td>
<td style="font-weight: bold; text-align:right">377</td>
<td style="font-weight: bold; text-align:right">911,951,216</td>
<td style="font-weight: bold; text-align:right">648,323</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,650</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">39,401,170</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">162,643                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">38,729,049</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">509,478</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">600,769</td>
<td style="font-weight: bold; text-align:right">2,480</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>403</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">7,768</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">37,509,539</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">162,688                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,831,800</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,900</td>
<td style="text-align:right;font-weight:bold;">515,051</td>
<td style="font-weight: bold; text-align:right">1,406</td>
<td style="font-weight: bold; text-align:right">447,162</td>
<td style="font-weight: bold; text-align:right">1,939</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>516</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,140</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">36,500,341</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">694,900                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">35,247,755</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">557,686</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">169,490</td>
<td style="font-weight: bold; text-align:right">3,227</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>310</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,590</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">30,473,569</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+190,538</td>
<td style="font-weight: bold; text-align:right;">59,822                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+407</td>
<td style="font-weight: bold; text-align:right">21,257,687</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+10,719</td>
<td style="text-align:right;font-weight:bold;">9,156,060</td>
<td style="font-weight: bold; text-align:right">671</td>
<td style="font-weight: bold; text-align:right">242,653</td>
<td style="font-weight: bold; text-align:right">476</td>
<td style="font-weight: bold; text-align:right">87,294,964</td>
<td style="font-weight: bold; text-align:right">695,108</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>2,099</td><td>1</td>
<td style="font-weight: bold; text-align:right">1,517</td>
<td style="font-weight: bold; text-align:right">3</td>
<td style="font-weight: bold; text-align:right">72,907</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">29,520,600</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+46,766</td>
<td style="font-weight: bold; text-align:right;">32,590                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+34</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">28,358,090</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+88,112</td>
<td style="text-align:right;font-weight:bold;">1,129,920</td>
<td style="font-weight: bold; text-align:right">526</td>
<td style="font-weight: bold; text-align:right">575,115</td>
<td style="font-weight: bold; text-align:right">635</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,575</td><td>3</td>
<td style="font-weight: bold; text-align:right">911</td>
<td style="font-weight: bold; text-align:right">0.7</td>
<td style="font-weight: bold; text-align:right">22,013</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,279,682</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">185,417                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">24,688,083</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">406,182</td>
<td style="font-weight: bold; text-align:right">319</td>
<td style="font-weight: bold; text-align:right">419,491</td>
<td style="font-weight: bold; text-align:right">3,077</td>
<td style="font-weight: bold; text-align:right">263,414,564</td>
<td style="font-weight: bold; text-align:right">4,371,100</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>325</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,740</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,210,131</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">201,028                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,874,846</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">134,257</td>
<td style="font-weight: bold; text-align:right">146</td>
<td style="font-weight: bold; text-align:right">353,443</td>
<td style="font-weight: bold; text-align:right">2,935</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>341</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,960</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">21,826,982</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,127</td>
<td style="font-weight: bold; text-align:right;">394,080                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+45</td>
<td style="font-weight: bold; text-align:right">21,245,559</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,694</td>
<td style="text-align:right;font-weight:bold;">187,343</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">149,699</td>
<td style="font-weight: bold; text-align:right">2,703</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>7</td><td>370</td><td>1</td>

In [4]:
table_code = codes.table
table_code

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>122,004,226</td>
<td></td>
<td>1,582,327</td>
<td></td>
<td>116,661,411</td>
<td>+2,541</td>
<td>3,760,488</td>
<td>10,260</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>209,278,066</td>
<td>+260,914</td>
<td>1,516,422</td>
<td>+477</td>
<td>194,552,674</td>
<td>+109,061</td>
<td>13,208,970</td>
<td>16,218</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>243,620,216</td>
<td>+3,402</td>
<td>1,989,034</td>
<td>+51</td>
<td>238,230,364</td>
<td>+20,262</td>
<td>3,400,818</td>
<td>7,429</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>67,175,673</td>
<td></td>
<td>1,343,494</td>
<td></td>
<td>64,761,096</td>
<td>+2,549</td>
<td>1,071,083</td>
<td>10,330</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>13,730,218</td>
<td></td>
<td>23,701</td>
<td></td>
<td>13,450,170</td>
<td></td>
<td>256,347</td>
<td>157</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,745,763</td>
<td></td>
<td>258,374</td>
<td></td>
<td>12,042,984</td>
<td></td>
<td>444,405</td>
<td>837</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>668,554,883</td>
<td>+264,316</td>
<td>6,713,367</td>
<td>+528</td>
<td>639,699,405</td>
<td>+134,413</td>
<td>22,142,111</td>
<td>45,231</td>
<td>85,769</td>
<td>861.3</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">103,081,401</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,121,089                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">99,876,630</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">2,083,682</td>
<td style="font-weight: bold; text-align:right">5,077</td>
<td style="font-weight: bold; text-align:right">307,885</td>
<td style="font-weight: bold; text-align:right">3,348</td>
<td style="font-weight: bold; text-align:right">1,155,402,577</td>
<td style="font-weight: bold; text-align:right">3,450,969</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>299</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,224</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,681,017</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">530,720                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,146,781</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">3,516</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">31,765</td>
<td style="font-weight: bold; text-align:right">377</td>
<td style="font-weight: bold; text-align:right">911,951,216</td>
<td style="font-weight: bold; text-align:right">648,323</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,650</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">39,401,170</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">162,643                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">38,729,049</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">509,478</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">600,769</td>
<td style="font-weight: bold; text-align:right">2,480</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>403</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">7,768</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">37,509,539</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">162,688                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,831,800</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,900</td>
<td style="text-align:right;font-weight:bold;">515,051</td>
<td style="font-weight: bold; text-align:right">1,406</td>
<td style="font-weight: bold; text-align:right">447,162</td>
<td style="font-weight: bold; text-align:right">1,939</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>516</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,140</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">36,500,341</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">694,900                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">35,247,755</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">557,686</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">169,490</td>
<td style="font-weight: bold; text-align:right">3,227</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>310</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,590</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">30,473,569</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+190,538</td>
<td style="font-weight: bold; text-align:right;">59,822                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+407</td>
<td style="font-weight: bold; text-align:right">21,257,687</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+10,719</td>
<td style="text-align:right;font-weight:bold;">9,156,060</td>
<td style="font-weight: bold; text-align:right">671</td>
<td style="font-weight: bold; text-align:right">242,653</td>
<td style="font-weight: bold; text-align:right">476</td>
<td style="font-weight: bold; text-align:right">87,294,964</td>
<td style="font-weight: bold; text-align:right">695,108</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>2,099</td><td>1</td>
<td style="font-weight: bold; text-align:right">1,517</td>
<td style="font-weight: bold; text-align:right">3</td>
<td style="font-weight: bold; text-align:right">72,907</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">29,520,600</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+46,766</td>
<td style="font-weight: bold; text-align:right;">32,590                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+34</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">28,358,090</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+88,112</td>
<td style="text-align:right;font-weight:bold;">1,129,920</td>
<td style="font-weight: bold; text-align:right">526</td>
<td style="font-weight: bold; text-align:right">575,115</td>
<td style="font-weight: bold; text-align:right">635</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,575</td><td>3</td>
<td style="font-weight: bold; text-align:right">911</td>
<td style="font-weight: bold; text-align:right">0.7</td>
<td style="font-weight: bold; text-align:right">22,013</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,279,682</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">185,417                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">24,688,083</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">406,182</td>
<td style="font-weight: bold; text-align:right">319</td>
<td style="font-weight: bold; text-align:right">419,491</td>
<td style="font-weight: bold; text-align:right">3,077</td>
<td style="font-weight: bold; text-align:right">263,414,564</td>
<td style="font-weight: bold; text-align:right">4,371,100</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>325</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,740</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,210,131</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">201,028                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,874,846</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">134,257</td>
<td style="font-weight: bold; text-align:right">146</td>
<td style="font-weight: bold; text-align:right">353,443</td>
<td style="font-weight: bold; text-align:right">2,935</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>341</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,960</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">21,826,982</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,127</td>
<td style="font-weight: bold; text-align:right;">394,080                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+45</td>
<td style="font-weight: bold; text-align:right">21,245,559</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,694</td>
<td style="text-align:right;font-weight:bold;">187,343</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">149,699</td>
<td style="font-weight: bold; text-align:right">2,703</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>7</td><td>370</td><td>1</td>

In [5]:
tags = table_code.find_all('tr')
tags

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">Tot Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>122,004,226</td>
 <td></td>
 <td>1,582,327</td>
 <td></td>
 <td>116,661,411</td>
 <td>+2,541</td>
 <td>3,760,488</td>
 <td>10,260</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>209,278,066</td>
 <td>+260,914</td>
 <td>1,516,422</td>
 <td>+477</td>
 <td>194,552,674</td>
 <td>+109,061</td>
 <td>13,208,970</td>
 <td>16,218</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>243,620,216</td>
 <td>+3,402</td>
 <td>1,989,034</td>
 <td>+51</td>
 <td>238,230,364</td>
 <td>+20,262</td>
 <td>3,400,818</td>
 <td>7,429</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>67,175,673</td>
 <td></td>
 <td>1,343,494</td>
 <td></td>
 <td>64,761,096</td>
 <td>+2,549</td>
 <td>1,071,083</td>
 <td>10,330</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>13,730,218</td>
 <td></td>
 <td>23,701</td>
 <td></td>
 <td>13,450,170</td>
 <td></td>
 <td>256,347</td>
 <td>157</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,745,763</td>
 <td></td>
 <td>258,374</td>
 <td></td>
 <td>12,042,984</td>
 <td></td>
 <td>444,405</td>
 <td>837</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>668,554,883</td>
 <td>+264,316</td>
 <td>6,713,367</td>
 <td>+528</td>
 <td>639,699,405</td>
 <td>+134,413</td>
 <td>22,142,111</td>
 <td>45,231</td>
 <td>85,769</td>
 <td>861.3</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">103,081,401</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,121,089                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">99,876,630</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">2,083,682</td>
 <td style="font-weight: bold; text-align:right">5,077</td>
 <td style="font-weight: bold; text-align:right">307,885</td>
 <td style="font-weight: bold; text-align:right">3,348</td>
 <td style="font-weight: bold; text-align:right">1,155,402,577</td>
 <td style="font-weight: bold; text-align:right">3,450,969</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>299</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">6,224</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">44,681,017</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">530,720                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">44,146,781</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">3,516</td>
 <td style="font-weight: bold; text-align:right">698</td>
 <td style="font-weight: bold; text-align:right">31,765</td>
 <td style="font-weight: bold; text-align:right">377</td>
 <td style="font-weight: bold; text-align:right">911,951,216</td>
 <td style="font-weight: bold; text-align:right">648,323</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,650</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">39,401,170</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">162,643                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">38,729,049</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">509,478</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">600,769</td>
 <td style="font-weight: bold; text-align:right">2,480</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>403</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">7,768</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">37,509,539</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">162,688                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,831,800</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,900</td>
 <td style="text-align:right;font-weight:bold;">515,051</td>
 <td style="font-weight: bold; text-align:right">1,406</td>
 <td style="font-weight: bold; text-align:right">447,162</td>
 <td style="font-weight: bold; text-align:right">1,939</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>516</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">6,140</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">36,500,341</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">694,900                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">35,247,755</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">557,686</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">169,490</td>
 <td style="font-weight: bold; text-align:right">3,227</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>310</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,590</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">30,473,569</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+190,538</td>
 <td style="font-weight: bold; text-align:right;">59,822                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+407</td>
 <td style="font-weight: bold; text-align:right">21,257,687</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+10,719</td>
 <td style="text-align:right;font-weight:bold;">9,156,060</td>
 <td style="font-weight: bold; text-align:right">671</td>
 <td style="font-weight: bold; text-align:right">242,653</td>
 <td style="font-weight: bold; text-align:right">476</td>
 <td style="font-weight: bold; text-align:right">87,294,964</td>
 <td style="font-weight: bold; text-align:right">695,108</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>2,099</td><td>1</td>
 <td style="font-weight: bold; text-align:right">1,517</td>
 <td style="font-weight: bold; text-align:right">3</td>
 <td style="font-weight: bold; text-align:right">72,907</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">29,520,600</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+46,766</td>
 <td style="font-weight: bold; text-align:right;">32,590                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+34</td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">28,358,090</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+88,112</td>
 <td style="text-align:right;font-weight:bold;">1,129,920</td>
 <td style="font-weight: bold; text-align:right">526</td>
 <td style="font-weight: bold; text-align:right">575,115</td>
 <td style="font-weight: bold; text-align:right">635</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>1,575</td><td>3</td>
 <td style="font-weight: bold; text-align:right">911</td>
 <td style="font-weight: bold; text-align:right">0.7</td>
 <td style="font-weight: bold; text-align:right">22,013</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">25,279,682</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">185,417                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">24,688,083</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">406,182</td>
 <td style="font-weight: bold; text-align:right">319</td>
 <td style="font-weight: bold; text-align:right">419,491</td>
 <td style="font-weight: bold; text-align:right">3,077</td>
 <td style="font-weight: bold; text-align:right">263,414,564</td>
 <td style="font-weight: bold; text-align:right">4,371,100</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>325</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">6,740</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,210,131</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">201,028                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,874,846</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">134,257</td>
 <td style="font-weight: bold; text-align:right">146</td>
 <td style="font-weight: bold; text-align:right">353,443</td>
 <td style="font-weight: bold; text-align:right">2,935</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>341</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,960</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">21,826,982</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,127</td>
 <td style="font-weight: bold; text-align:right;">394,080                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+45</td>
 <td style="font-weight: bold; text-align:right">21,245,559</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,694</td>
 <td style="text-align:right;font-weight:bold;">187,343</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">149,699</td>
 <td style="font-weight: bold; text-align:right">2,703</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>

In [6]:
for tag in tags:
    print(tag.text)

#
Country,Other
TotalCases
NewCases
TotalDeaths
NewDeaths
TotalRecovered
NewRecovered
ActiveCases
Serious,Critical
Tot Cases/1M pop
Deaths/1M pop
TotalTests
Tests/
1M pop

Population
Continent
1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl
New Cases/1M pop
New Deaths/1M pop
Active Cases/1M pop




North America

122,004,226

1,582,327

116,661,411
+2,541
3,760,488
10,260





North America














Asia

209,278,066
+260,914
1,516,422
+477
194,552,674
+109,061
13,208,970
16,218





Asia














Europe

243,620,216
+3,402
1,989,034
+51
238,230,364
+20,262
3,400,818
7,429





Europe














South America

67,175,673

1,343,494

64,761,096
+2,549
1,071,083
10,330





South America














Oceania

13,730,218

23,701

13,450,170

256,347
157





Australia/Oceania














Africa

12,745,763

258,374

12,042,984

444,405
837





Africa
















721

15

706

0
0



















World
668,554,883
+264,316
6,713,367
+528
639,699,405
+134,413
22,142,111
45,231
85,769
861.3



All












1
USA
103,081,401

1,121,089

99,876,630

2,083,682
5,077
307,885
3,348
1,155,402,577
3,450,969
334,805,269
North America

32990


6,224


2
India
44,681,017

530,720

44,146,781

3,516
698
31,765
377
911,951,216
648,323
1,406,631,776
Asia

312,6502


2


3
France
39,401,170

162,643

38,729,049

509,478
869
600,769
2,480
271,490,188
4,139,547
65,584,518
Europe

24030


7,768


4
Germany
37,509,539

162,688

36,831,800
+5,900
515,051
1,406
447,162
1,939
122,332,384
1,458,359
83,883,596
Europe

25161


6,140


5
Brazil
36,500,341

694,900

35,247,755

557,686
8,318
169,490
3,227
63,776,166
296,146
215,353,593
South America

63103


2,590


6
Japan
30,473,569
+190,538
59,822
+407
21,257,687
+10,719
9,156,060
671
242,653
476
87,294,964
695,108
125,584,838
Asia

42,0991
1,517
3
72,907


7
S. Korea
29,520,600
+46,766
32,590
+34
28,358,090
+88,112
1,129,920
526
575,115
635
15,804,065
307,892
51,329,899
Asia

21,5753
911
0.7
22,013


8
Italy
25,279,682

185,417

24,688,083

406,182
319
419,491
3,077
263,414,564
4,371,100
60,262,770
Europe

23250


6,740


9
UK
24,210,131

201,028

23,874,846

134,257
146
353,443
2,935
522,526,476
7,628,357
68,497,907
Europe

33410


1,960


10
Russia
21,826,982
+3,127
394,080
+45
21,245,559
+3,694
187,343
2,300
149,699
2,703
273,400,000
1,875,095
145,805,947
Europe

73701
21
0.3
1,285


11
Turkey
17,042,722

101,492

N/A
N/A
N/A

199,186
1,186
162,743,369
1,902,052
85,561,976
Asia

58431


1,819


12
Spain
13,693,478

117,413

13,502,806

73,259
231
293,102
2,513
471,036,328
10,082,298
46,719,142
Europe

33980


1,568


13
Vietnam
11,525,711

43,186

10,611,494

871,031
23
116,476
436
85,826,548
867,342
98,953,541
Asia

92,2911


8,802


14
Australia
11,205,520

17,304

11,052,693

135,523
124
429,844
664
78,835,048
3,024,116
26,068,792
Australia/Oceania

21,5070


5,199


15
Argentina
9,963,697

130,171

9,636,804

196,722
402
216,554
2,829
35,716,069
776,264
46,010,234
South America

53531


4,276


16
Taiwan
9,055,191
+23,411
15,542
+36
8,572,902
+10,298
466,747

379,059
651
29,524,201
1,235,912
23,888,595
Asia

31,5371
980
2
19,538


17
Netherlands
8,574,631

22,989

8,526,387
+1,126
25,255
55
498,193
1,336
25,984,435
1,509,718
17,211,447
Europe

27491


1,467


18
Iran
7,561,808

144,706

7,336,407

80,695
153
87,905
1,682
54,420,785
632,632
86,022,837
Asia

115942


938


19
Mexico
7,271,010

331,263

6,503,502

436,245
4,798
55,266
2,518
19,042,684
144,742
131,562,772
North America

183977


3,316


20
Indonesia
6,723,201

160,679

6,554,066

8,456
2,771
24,086
576
114,158,919
408,975
279,134,505
Asia

421,7372


30


21
Poland
6,371,259
+143
118,586

5,335,940

916,733
1,192
168,821
3,142
38,021,654
1,007,469
37,739,785
Europe

63181
4

24,291


22
Colombia
6,349,971

142,259

6,170,360

37,352
342
123,270
2,762
36,951,507
717,327
51,512,762
South America

83621


725


23
Austria
5,724,215

21,484

5,666,495

36,236

631,344
2,370
204,767,733
22,584,568
9,066,710
Europe

24220


3,997


24
Portugal
5,557,941

25,805

5,523,729
+289
8,407
61
548,090
2,545
45,826,501
4,519,125
10,140,570
Europe

23930


829


25
Greece
5,548,487

34,779

5,513,708

0
115
537,819
3,371
102,228,365
9,909,078
10,316,637
Europe

22970





26
Ukraine
5,361,352

110,859

5,242,011
+576
8,482

124,128
2,567
32,603,805
754,855
43,192,122
Europe

83901


196


27
Chile
5,062,734

63,330

4,986,896

12,508
113
262,997
3,290
47,804,159
2,483,308
19,250,195
South America

43040


650


28
Malaysia
5,029,908

36,874

4,981,603

11,431
34
151,590
1,111
67,275,350
2,027,522
33,181,072
Asia

79000


345


29
DPRK
4,772,813

74

4,772,739

0

183,636
3


25,990,679
Asia

5351,225





30
Israel
4,770,244

12,079

4,748,068

10,097
57
511,499
1,295
41,373,364
4,436,346
9,326,000
Asia

27720


1,083


31
Thailand
4,723,919

33,669

4,690,108

142
1,496
67,409
480
17,270,775
246,450
70,078,203
Asia

152,0814


2


32
Belgium
4,682,234

33,395

4,614,647
+1,188
34,192
97
401,279
2,862
36,436,600
3,122,706
11,668,278
Europe

23490


2,930


33
Czechia
4,582,935
+81
42,200
+1
4,535,854
+536
4,881
43
426,844
3,930
56,812,823
5,291,419
10,736,784
Europe

22540
8
0.09
455


34
Canada
4,475,268

48,948

4,386,809
+2,541
39,511
99
116,579
1,275
66,343,123
1,728,207
38,388,419
North America

97841


1,029


35
Peru
4,466,331

218,356

4,225,300
+1,439
22,675
109
132,594
6,482
37,438,974
1,111,470
33,684,208
South America

81541


673


36
Switzerland
4,382,359

14,388

4,331,160
+5,197
36,811
63
499,492
1,640
23,292,004
2,654,772
8,773,637
Europe

26100


4,196


37
Philippines
4,067,170

65,464

3,989,188

12,518
162
36,150
582
34,073,949
302,855
112,508,994
Asia

281,7193


111


38
South Africa
4,050,050

102,568

3,912,506

34,976
192
66,661
1,688
26,473,049
435,726
60,756,135
Africa

155922


576


39
Romania
3,312,085

67,408

3,237,640

7,037
110
174,033
3,542
26,082,014
1,370,477
19,031,335
Europe

62821


370


40
Denmark
3,169,858

7,889

3,154,368

7,601
17
543,254
1,352
129,060,758
22,118,571
5,834,950
Europe

27400


1,303


41
Hong Kong
2,755,827

12,276

2,126,102

617,449
54
362,404
1,614
75,375,235
9,912,187
7,604,299
Asia

36190


81,197


42
Sweden
2,683,356

22,110

2,619,890
+1,628
41,356
43
262,586
2,164
19,333,094
1,891,883
10,218,971
Europe

44621


4,047


43
Iraq
2,465,545

25,375

2,439,497

673
21
58,474
602
19,544,451
463,523
42,164,965
Asia

171,6622


16


44
Serbia
2,452,493

17,558

2,418,818

16,117
24
283,426
2,029
11,925,792
1,378,224
8,653,016
Europe

44931


1,863


45
Singapore
2,207,670

1,712

2,133,654

72,304
2
371,440
288
24,755,451
4,165,098
5,943,546
Asia

33,4720


12,165


46
Hungary
2,188,737

48,546

2,127,121

13,070
16
227,845
5,054
11,394,556
1,186,160
9,606,259
Europe

41981


1,361


47
New Zealand
2,117,094

3,568

2,092,041

21,485

432,219
728
7,710,637
1,574,177
4,898,203
Australia/Oceania

21,3731


4,386


48
Bangladesh
2,037,250

29,440

1,988,475

19,335
1,331
12,135
175
15,160,408
90,302
167,885,689
Asia

825,70311


115


49
Slovakia
1,859,692
+24
20,845
+4
1,837,846
+31
1,001
28
340,591
3,818
7,377,939
1,351,223
5,460,193
Europe

32621
4
0.7
183


50
Georgia
1,809,359

16,899

1,776,548

15,912

455,903
4,258
16,920,079
4,263,340
3,968,738
Asia

22350


4,009


51
Jordan
1,746,997

14,122

1,731,007

1,868
59
169,597
1,371
17,201,885
1,669,945
10,300,869
Asia

67291


181


52
Ireland
1,693,847

8,339

1,674,770
+251
10,738
36
337,406
1,661
12,939,937
2,577,575
5,020,199
Europe

36020


2,139


53
Pakistan
1,575,953
+18
30,638

1,538,689

6,626
22
6,867
134
30,570,862
133,213
229,488,994
Asia

1467,4908
0.08

29


54
Norway
1,476,206

4,571

1,468,933

2,702
20
267,847
829
11,002,430
1,996,315
5,511,370
Europe

41,2061


490


55
Finland
1,446,397

8,263

1,421,408
+1,580
16,726
21
260,379
1,487
11,984,148
2,157,378
5,554,960
Europe

46720


3,011


56
Kazakhstan
1,404,104
+169
13,695

1,383,020

7,389
24
73,111
713
11,575,012
602,707
19,205,043
Asia

141,4022
9

385


57
Slovenia
1,313,501

7,025

1,292,579

13,897
21
632,088
3,381
2,811,092
1,352,765
2,078,034
Europe

22961


6,688


58
Bulgaria
1,293,216

38,122

1,251,048

4,046
40
188,940
5,570
10,917,308
1,595,026
6,844,597
Europe

51801


591


59
Lithuania
1,290,919
+27
9,502
+1
1,274,028
+125
7,389
8
484,996
3,570
10,324,083
3,878,744
2,661,708
Europe

22800
10
0.4
2,776


60
Morocco
1,271,868

16,295

1,255,219

354
293
33,672
431
12,876,656
340,898
37,772,756
Africa

302,3183


9


61
Croatia
1,265,333

17,669

1,245,723

1,941
36
311,713
4,353
5,437,406
1,339,498
4,059,286
Europe

32301


478


62
Lebanon
1,223,536

10,752

1,087,587

125,197
74
183,031
1,608
4,795,578
717,380
6,684,849
Asia

56221


18,728


63
Guatemala
1,211,008

20,017

1,174,756

16,235
5
65,164
1,077
6,587,246
354,457
18,584,039
North America

159283


874


64
Costa Rica
1,171,802

9,104

860,711

301,987
52
226,114
1,757
4,659,757
899,158
5,182,354
North America

45691


58,272


65
Bolivia
1,168,711

22,315

1,113,655

32,741
220
97,452
1,861
2,705,422
225,590
11,992,656
South America

105374


2,730


66
Tunisia
1,147,645

29,285

N/A
N/A
N/A
44
95,267
2,431
4,985,258
413,829
12,046,656
Africa

104112


694


67
Cuba
1,112,134

8,530

1,103,455

149
23
98,370
754
14,276,770
1,262,799
11,305,652
North America

101,3251


13


68
UAE
1,047,371

2,348

1,030,367

14,656

103,887
233
198,071,556
19,646,477
10,081,785
Asia

104,2940


1,454


69
Ecuador
1,040,463

35,940

1,000,080
+1,110
4,443
759
57,442
1,984
3,082,403
170,173
18,113,361
South America

175046


245


70
Panama
1,025,844

8,575

1,014,270

2,999
16
230,684
1,928
7,404,783
1,665,132
4,446,964
North America

45191


674


71
Uruguay
1,020,161

7,570

1,004,306

8,285
18
291,807
2,165
6,114,822
1,749,083
3,496,016
South America

34621


2,370


72
Mongolia
1,007,765

2,179

1,005,087

499
192
298,325
645
4,030,048
1,193,000
3,378,078
Asia

31,5501


148


73
Nepal
1,001,020

12,020

988,979

21

33,118
398
5,992,656
198,264
30,225,582
Asia

302,5155


0.7


74
Belarus
994,037

7,118

985,592

1,327

105,381
755
13,646,641
1,446,722
9,432,800
Europe

91,3251


141


75
Latvia
974,574

6,177

966,418

1,979
13
527,128
3,341
7,851,262
4,246,595
1,848,837
Europe

22990


1,070


76
Saudi Arabia
827,190

9,529

814,821

2,840
18
23,077
266
44,963,615
1,254,393
35,844,909
Asia

433,7621


79


77
Azerbaijan
826,803

10,017

816,382

404

80,271
973
7,441,759
722,486
10,300,205
Asia

121,0281


39


78
Paraguay
798,231

19,716

N/A
N/A
N/A
7
109,259
2,699
2,657,506
363,751
7,305,843
South America

93713


10,977


79
Bahrain
699,137

1,539

697,064

534
11
391,897
863
10,645,441
5,967,232
1,783,983
Asia

31,1590


299


80
Sri Lanka
671,927

16,818

655,072

37

31,143
779
6,486,117
300,619
21,575,842
Asia

321,2833


2


81
Kuwait
662,747

2,570

660,095

82

151,301
587
8,447,300
1,928,464
4,380,326
Asia

71,7041


19


82
Dominican Republic
650,990

4,384

644,785

1,821
4
58,879
397
3,740,928
338,350
11,056,370
North America

172,5223


165


83
Cyprus
634,709

1,262

624,300

9,147
60
518,813
1,032
9,640,118
7,879,860
1,223,387
Asia

29690


7,477


84
Myanmar
633,713

19,490

608,346

5,877

11,475
353
9,845,419
178,271
55,227,143
Asia

872,8346


106


85
Palestine
621,008

5,404

615,445

159
17
116,173
1,011
3,078,533
575,907
5,345,541
Asia

99892


30


86
Estonia
612,432

2,872

524,990

84,570
11
463,293
2,173
3,638,453
2,752,421
1,321,910
Europe

24600


63,976


87
Moldova
596,914

11,936

504,142

80,836
49
148,739
2,974
3,216,305
801,437
4,013,171
Europe

73361


20,143


88
Venezuela
550,740

5,834

543,956

950
36
18,818
199
3,359,014
114,771
29,266,991
South America

535,0179


32


89
Egypt
515,645

24,613

442,182

48,850
122
4,857
232
3,693,367
34,792
106,156,692
Africa

2064,31329


460


90
Libya
507,153

6,437

500,675

41

72,031
914
2,483,446
352,725
7,040,745
Africa

141,0943


6


91
Ethiopia
498,660

7,572

482,606

8,482

4,128
63
5,431,905
44,961
120,812,698
Africa

24215,95522


70


92
Qatar
490,493

685

489,258

550
1
164,600
230
4,065,369
1,364,257
2,979,915
Asia

64,3501


185


93
Réunion
480,501

907

418,572

61,022
10
529,151
999
1,603,660
1,766,027
908,061
Africa

21,0011


67,200


94
Honduras
468,048

11,088

N/A
N/A
N/A
105
45,792
1,085
1,602,425
156,774
10,221,247
North America

229226


31,739


95
Armenia
445,976

8,716

435,162

2,098

150,061
2,933
3,242,901
1,091,164
2,971,966
Asia

73411


706


96
Bosnia and Herzegovina
401,083

16,234

378,846

6,003

123,436
4,996
1,882,568
579,373
3,249,317
Europe

82002


1,847


97
Oman
399,154

4,260

384,669

10,225
2
74,973
800
25,000,000
4,695,724
5,323,993
Asia

131,2500


1,921


98
North Macedonia
345,857

9,614

335,979

264

166,173
4,619
2,208,755
1,061,236
2,081,304
Europe

62161


127


99
Kenya
342,598

5,688

336,791

119
1
6,094
101
3,960,657
70,455
56,215,221
Africa

1649,88314


2


100
Zambia
335,545

4,028

330,301

1,216

17,234
207
3,797,662
195,050
19,470,234
Africa

584,8345


62


101
Albania
333,916

3,595

328,670

1,651

116,494
1,254
1,941,032
677,173
2,866,374
Europe

97971


576


102
Botswana
328,071

2,794

323,747

1,530
1
134,391
1,145
2,026,898
830,300
2,441,162
Africa

78741


627


103
Luxembourg
297,757

1,133

288,991

7,633

463,528
1,764
4,412,567
6,869,188
642,371
Europe

25670


11,883


104
Montenegro
285,031

2,791

281,852

388
6
453,907
4,445
2,681,486
4,270,222
627,950
Europe

22250


618


105
Algeria
271,254

6,881

182,660

81,713

5,981
152
230,861
5,091
45,350,148
Africa

1676,591196


1,802


106
Brunei
270,199

225

243,601

26,373
3
606,601
505
717,784
1,611,437
445,431
Asia

21,9801


59,208


107
Nigeria
266,463

3,155

259,850

3,458
11
1,229
15
5,708,974
26,339
216,746,934
Africa

81368,70038


16


108
Zimbabwe
259,981

5,637

253,677

667
12
16,957
368
2,525,756
164,744
15,331,428
Africa

592,7206


44


109
Uzbekistan
249,867

1,637

241,486

6,744
23
7,267
48
1,377,915
40,077
34,382,084
Asia

13821,00325


196


110
Mozambique
230,970

2,230

228,663

77
11
6,980
67
1,371,127
41,437
33,089,461
Africa

14314,83824


2


111
Martinique
225,249

1,079

N/A
N/A
N/A
8
602,130
2,884
828,928
2,215,870
374,087
North America

23470


598,968


112
Laos
217,863
+6
758

N/A
N/A
N/A

29,122
101
1,233,207
164,845
7,481,023
Asia

349,8696
0.8

27,997


113
Iceland
208,298

229

N/A
N/A
N/A
2
603,075
663
1,996,384
5,780,036
345,393
Europe

21,5080


383,285


114
Afghanistan
207,766

7,850

185,612

14,304
1,124
5,098
193
1,179,929
28,952
40,754,388
Asia

1965,19235


351


115
Kyrgyzstan
206,567

2,991

196,406

7,170
131
30,701
445
1,907,195
283,460
6,728,271
Asia

332,2504


1,066


116
El Salvador
201,785

4,230

179,410

18,145
8
30,805
646
2,610,114
398,467
6,550,389
North America

321,5493


2,770


117
Guadeloupe
199,988

999

N/A
N/A
N/A
19
500,228
2,499
938,039
2,346,306
399,794
North America

24000


492,101


118
Trinidad and Tobago
186,279

4,289

181,831

159
8
132,434
3,049
879,730
625,437
1,406,585
North America

83282


113


119
Maldives
185,693

311

163,687

21,695
25
343,250
575
2,213,831
4,092,223
540,985
Asia

31,7400


40,103


120
Ghana
171,065

1,461

169,586

18
2
5,281
45
2,525,056
77,945
32,395,450
Africa

18922,17313


0.6


121
Namibia
170,295

4,082

165,961

252

64,656
1,550
1,062,663
403,460
2,633,874
Africa

156452


96


122
Uganda
169,985

3,630

100,431

65,924
3
3,510
75
3,012,408
62,198
48,432,863
Africa

28513,34216


1,361


123
Jamaica
152,791

3,464

101,996

47,331

51,185
1,160
1,183,986
396,633
2,985,094
North America

208623


15,856


124
Cambodia
138,628
+6
3,056

135,547
+8
25

8,074
178
3,091,420
180,062
17,168,639
Asia

1245,6186
0.3

1


125
Rwanda
133,033

1,468

131,112

453

9,782
108
5,882,479
432,520
13,600,464
Africa

1029,2652


33


126
Cameroon
123,993

1,965

118,616

3,412
13
4,442
70
1,751,774
62,762
27,911,548
Africa

22514,20416


122


127
Malta
116,630

821

115,025

784
4
262,661
1,849
2,101,922
4,733,707
444,033
Europe

45410


1,766


128
Barbados
105,515

568

104,913

34

366,342
1,972
786,526
2,730,775
288,023
North America

35070


118


129
Angola
105,095

1,930

103,050

115

3,000
55
1,499,795
42,818
35,027,343
Africa

33318,14923


3


130
Channel Islands
100,373

219

99,304

850

568,805
1,241
1,252,808
7,099,551
176,463
Europe

28060


4,817


131
French Guiana
97,946

415

11,254

86,277
6
311,762
1,321
651,257
2,072,951
314,169
South America

37570


274,620


132
DRC
95,173

1,462

84,159

9,552

999
15
846,704
8,890
95,240,792
Africa

1,00165,144112


100


133
Senegal
88,900

1,968

86,915

17

5,036
111
1,146,543
64,946
17,653,671
Africa

1998,97015


1.0


134
Malawi
88,220

2,685

85,065

470
67
4,371
133
624,784
30,959
20,180,839
Africa

2297,51632


23


135
Ivory Coast
87,957

833

87,113

11

3,171
30
1,665,423
60,032
27,742,298
Africa

31533,30417


0.4


136
Suriname
82,020

1,398

N/A
N/A
N/A

137,426
2,342
239,603
401,459
596,831
South America

74272


51,802


137
New Caledonia
79,606

314

78,985

307
9
273,640
1,079
98,964
340,182
290,915
Australia/Oceania

49263


1,055


138
French Polynesia
77,957

649

N/A
N/A
N/A
7
274,338
2,284


284,164
Australia/Oceania

4438


154,164


139
Eswatini
74,034

1,422

72,590

22

62,486
1,200
1,048,081
884,593
1,184,817
Africa

168331


19


140
Guyana
72,397

1,290

70,778

329

91,175
1,625
712,103
896,804
794,045
South America

116161


414


141
Belize
70,174

688

69,336

150
6
170,247
1,669
576,016
1,397,453
412,190
North America

65991


364


142
Fiji
68,771

883

66,730

1,158

75,617
971
666,782
733,158
909,466
Australia/Oceania

131,0301


1,273


143
Madagascar
67,750

1,418

66,265

67

2,322
49
522,334
17,902
29,178,077
Africa

43120,57756


2


144
Sudan
63,702

4,995

58,233

474

1,385
109
562,941
12,240
45,992,020
Africa

7229,20882


10


145
Mauritania
63,429

997

62,423

9

12,939
203
1,009,957
206,030
4,901,981
Africa

774,9175


2


146
Cabo Verde
63,207

412

62,733

62
23
111,343
726
401,622
707,482
567,678
Africa

91,3781


109


147
Bhutan
62,538

21

61,564

953

79,369
27
2,303,734
2,923,739
787,941
Asia

1337,5210


1,209


148
Syria
57,423

3,163

54,260

0

2,965
163
146,269
7,553
19,364,809
Asia

3376,122132





149
Burundi
51,722

38

51,357

327

4,097
3
345,742
27,386
12,624,840
Africa

244332,23337


26


150
Seychelles
50,355

172

50,026

157

506,457
1,730


99,426
Africa

2578


1,579


151
Gabon
48,980

306

48,668

6

21,008
131
1,621,909
695,641
2,331,533
Africa

487,6191


3


152
Andorra
47,781

165

47,563

53
14
616,824
2,130
249,838
3,225,256
77,463
Europe

24690


684


153
Papua New Guinea
46,663

669

43,982

2,012
7
5,022
72
249,149
26,813
9,292,169
Australia/Oceania

19913,89037


217


154
Curaçao
45,986

295

44,720

971
3
277,812
1,782
496,693
3,000,640
165,529
North America

45610


5,866


155
Aruba
43,860

236

42,438

1,186
2
407,587
2,193
177,885
1,653,068
107,609
North America

24561


11,021


156
Tanzania
42,351

845

N/A
N/A
N/A
7
669
13


63,298,550
Africa

1,49574,910


653


157
Mayotte
42,002

188

N/A
N/A
N/A

146,727
657
176,919
618,038
286,259
Africa

71,5232


135,716


158
Mauritius
41,541

1,041

39,807

693

32,588
817
358,675
281,374
1,274,727
Africa

311,2254


544


159
Togo
39,346

290

39,048

8

4,533
33
804,930
92,725
8,680,837
Africa

22129,93411


0.9


160
Guinea
38,210

466

37,292

452
8
2,756
34
660,107
47,607
13,865,691
Africa

36329,75521


33


161
Isle of Man
38,008

116

N/A
N/A
N/A

443,335
1,353
150,753
1,758,422
85,732
Europe

27391


129,450


162
Bahamas
37,491

833

36,366

292
1
93,607
2,080
257,839
643,767
400,516
North America

114812


729


163
Lesotho
34,790

723

25,980

8,087

15,990
332
431,221
198,199
2,175,699
Africa

633,0095


3,717


164
Faeroe Islands
34,658

28

N/A
N/A
N/A
5
703,959
569
778,000
15,802,409
49,233
Europe

11,7580


547,133


165
Haiti
33,912

860

32,972

80

2,903
74
132,422
11,337
11,680,283
North America

34413,58288


7



In [7]:
list_data =[]
for tag in tags:
    
    list_data.append(tag.text)
    
    
list_data

['\n#\nCountry,Other\nTotalCases\nNewCases\nTotalDeaths\nNewDeaths\nTotalRecovered\nNewRecovered\nActiveCases\nSerious,Critical\nTot\xa0Cases/1M pop\nDeaths/1M pop\nTotalTests\nTests/\n1M pop\n\nPopulation\nContinent\n1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl\nNew Cases/1M pop\nNew Deaths/1M pop\nActive Cases/1M pop\n',
 '\n\n\nNorth America\n\n122,004,226\n\n1,582,327\n\n116,661,411\n+2,541\n3,760,488\n10,260\n\n\n\n\n\nNorth America\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nAsia\n\n209,278,066\n+260,914\n1,516,422\n+477\n194,552,674\n+109,061\n13,208,970\n16,218\n\n\n\n\n\nAsia\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nEurope\n\n243,620,216\n+3,402\n1,989,034\n+51\n238,230,364\n+20,262\n3,400,818\n7,429\n\n\n\n\n\nEurope\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nSouth America\n\n67,175,673\n\n1,343,494\n\n64,761,096\n+2,549\n1,071,083\n10,330\n\n\n\n\n\nSouth America\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nOceania\n\n13,730,218\n\n23,701\n\n13,450,170\n\n256,347\n157\n\n\n\n\n\nAustralia/Oceania\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\nAfrica\n\n12,745,763\n\n258,374\n\n12,042,984\n\n444,405\n837\n\n\n\n\n\nAfrica\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\n\n\n721\n\n15\n\n706\n\n0\n0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n',
 '\n\nWorld\n668,554,883\n+264,316\n6,713,367\n+528\n639,699,405\n+134,413\n22,142,111\n45,231\n85,769\n861.3\n\n\n\nAll\n\n\n\n\n\n\n\n\n\n\n',
 '\n1\nUSA\n103,081,401\n\n1,121,089                                \n\n99,876,630\n\n2,083,682\n5,077\n307,885\n3,348\n1,155,402,577\n3,450,969\n334,805,269 \nNorth America\n\n32990\n\n\n6,224\n',
 '\n2\nIndia\n44,681,017\n\n530,720                                \n\n44,146,781\n\n3,516\n698\n31,765\n377\n911,951,216\n648,323\n1,406,631,776 \nAsia\n\n312,6502\n\n\n2\n',
 '\n3\nFrance\n39,401,170\n\n162,643                                \n\n38,729,049\n\n509,478\n869\n600,769\n2,480\n271,490,188\n4,139,547\n65,584,518 \nEurope\n\n24030\n\n\n7,768\n',
 '\n4\nGermany\n37,509,539\n\n162,688                                \n\n36,831,800\n+5,900\n515,051\n1,406\n447,162\n1,939\n122,332,384\n1,458,359\n83,883,596 \nEurope\n\n25161\n\n\n6,140\n',
 '\n5\nBrazil\n36,500,341\n\n694,900                                \n\n35,247,755\n\n557,686\n8,318\n169,490\n3,227\n63,776,166\n296,146\n215,353,593 \nSouth America\n\n63103\n\n\n2,590\n',
 '\n6\nJapan\n30,473,569\n+190,538\n59,822                                \n+407\n21,257,687\n+10,719\n9,156,060\n671\n242,653\n476\n87,294,964\n695,108\n125,584,838 \nAsia\n\n42,0991\n1,517\n3\n72,907\n',
 '\n7\nS. Korea\n29,520,600\n+46,766\n32,590                                \n+34\n28,358,090\n+88,112\n1,129,920\n526\n575,115\n635\n15,804,065\n307,892\n51,329,899 \nAsia\n\n21,5753\n911\n0.7\n22,013\n',
 '\n8\nItaly\n25,279,682\n\n185,417                                \n\n24,688,083\n\n406,182\n319\n419,491\n3,077\n263,414,564\n4,371,100\n60,262,770 \nEurope\n\n23250\n\n\n6,740\n',
 '\n9\nUK\n24,210,131\n\n201,028                                \n\n23,874,846\n\n134,257\n146\n353,443\n2,935\n522,526,476\n7,628,357\n68,497,907 \nEurope\n\n33410\n\n\n1,960\n',
 '\n10\nRussia\n21,826,982\n+3,127\n394,080                                \n+45\n21,245,559\n+3,694\n187,343\n2,300\n149,699\n2,703\n273,400,000\n1,875,095\n145,805,947 \nEurope\n\n73701\n21\n0.3\n1,285\n',
 '\n11\nTurkey\n17,042,722\n\n101,492                                \n\nN/A\nN/A\nN/A\n\n199,186\n1,186\n162,743,369\n1,902,052\n85,561,976 \nAsia\n\n58431\n\n\n1,819\n',
 '\n12\nSpain\n13,693,478\n\n117,413                                \n\n13,502,806\n\n73,259\n231\n293,102\n2,513\n471,036,328\n10,082,298\n46,719,142 \nEurope\n\n33980\n\n\n1,568\n',
 '\n13\nVietnam\n11,525,711\n\n43,186                                \n\n10,611,494\n\n871,031\n23\n116,476\n436\n85,826,548\n867,342\n98,953,541 \nAsia\n\n92,2911\n\n\n8,802\n',
 '\n14\nAustralia\n11,205,520\n\n17,304                                \n\n11,052,693\n\n135,523\n124\n429,844\n664\n78,835,048\n3,024,116\n26,068,792 \nAustralia/Oceania\n\n21,5070\n\n\n5,199\n',
 '\n15\nArgentina\n9,963,697\n\n130,171                                \n\n9,636,804\n\n196,722\n402\n216,554\n2,829\n35,716,069\n776,264\n46,010,234 \nSouth America\n\n53531\n\n\n4,276\n',
 '\n16\nTaiwan\n9,055,191\n+23,411\n15,542                                \n+36\n8,572,902\n+10,298\n466,747\n\n379,059\n651\n29,524,201\n1,235,912\n23,888,595 \nAsia\n\n31,5371\n980\n2\n19,538\n',
 '\n17\nNetherlands\n8,574,631\n\n22,989                                \n\n8,526,387\n+1,126\n25,255\n55\n498,193\n1,336\n25,984,435\n1,509,718\n17,211,447 \nEurope\n\n27491\n\n\n1,467\n',
 '\n18\nIran\n7,561,808\n\n144,706                                \n\n7,336,407\n\n80,695\n153\n87,905\n1,682\n54,420,785\n632,632\n86,022,837 \nAsia\n\n115942\n\n\n938\n',
 '\n19\nMexico\n7,271,010\n\n331,263                                \n\n6,503,502\n\n436,245\n4,798\n55,266\n2,518\n19,042,684\n144,742\n131,562,772 \nNorth America\n\n183977\n\n\n3,316\n',
 '\n20\nIndonesia\n6,723,201\n\n160,679                                \n\n6,554,066\n\n8,456\n2,771\n24,086\n576\n114,158,919\n408,975\n279,134,505 \nAsia\n\n421,7372\n\n\n30\n',
 '\n21\nPoland\n6,371,259\n+143\n118,586                                \n\n5,335,940\n\n916,733\n1,192\n168,821\n3,142\n38,021,654\n1,007,469\n37,739,785 \nEurope\n\n63181\n4\n\n24,291\n',
 '\n22\nColombia\n6,349,971\n\n142,259                                \n\n6,170,360\n\n37,352\n342\n123,270\n2,762\n36,951,507\n717,327\n51,512,762 \nSouth America\n\n83621\n\n\n725\n',
 '\n23\nAustria\n5,724,215\n\n21,484                                \n\n5,666,495\n\n36,236\n\n631,344\n2,370\n204,767,733\n22,584,568\n9,066,710 \nEurope\n\n24220\n\n\n3,997\n',
 '\n24\nPortugal\n5,557,941\n\n25,805                                \n\n5,523,729\n+289\n8,407\n61\n548,090\n2,545\n45,826,501\n4,519,125\n10,140,570 \nEurope\n\n23930\n\n\n829\n',
 '\n25\nGreece\n5,548,487\n\n34,779                                \n\n5,513,708\n\n0\n115\n537,819\n3,371\n102,228,365\n9,909,078\n10,316,637 \nEurope\n\n22970\n\n\n\n',
 '\n26\nUkraine\n5,361,352\n\n110,859                                \n\n5,242,011\n+576\n8,482\n\n124,128\n2,567\n32,603,805\n754,855\n43,192,122 \nEurope\n\n83901\n\n\n196\n',
 '\n27\nChile\n5,062,734\n\n63,330                                \n\n4,986,896\n\n12,508\n113\n262,997\n3,290\n47,804,159\n2,483,308\n19,250,195 \nSouth America\n\n43040\n\n\n650\n',
 '\n28\nMalaysia\n5,029,908\n\n36,874                                \n\n4,981,603\n\n11,431\n34\n151,590\n1,111\n67,275,350\n2,027,522\n33,181,072 \nAsia\n\n79000\n\n\n345\n',
 '\n29\nDPRK\n4,772,813\n\n74                                \n\n4,772,739\n\n0\n\n183,636\n3\n\n\n25,990,679 \nAsia\n\n5351,225\n\n\n\n',
 '\n30\nIsrael\n4,770,244\n\n12,079                                \n\n4,748,068\n\n10,097\n57\n511,499\n1,295\n41,373,364\n4,436,346\n9,326,000 \nAsia\n\n27720\n\n\n1,083\n',
 '\n31\nThailand\n4,723,919\n\n33,669                                \n\n4,690,108\n\n142\n1,496\n67,409\n480\n17,270,775\n246,450\n70,078,203 \nAsia\n\n152,0814\n\n\n2\n',
 '\n32\nBelgium\n4,682,234\n\n33,395                                \n\n4,614,647\n+1,188\n34,192\n97\n401,279\n2,862\n36,436,600\n3,122,706\n11,668,278 \nEurope\n\n23490\n\n\n2,930\n',
 '\n33\nCzechia\n4,582,935\n+81\n42,200                                \n+1\n4,535,854\n+536\n4,881\n43\n426,844\n3,930\n56,812,823\n5,291,419\n10,736,784 \nEurope\n\n22540\n8\n0.09\n455\n',
 '\n34\nCanada\n4,475,268\n\n48,948                                \n\n4,386,809\n+2,541\n39,511\n99\n116,579\n1,275\n66,343,123\n1,728,207\n38,388,419 \nNorth America\n\n97841\n\n\n1,029\n',
 '\n35\nPeru\n4,466,331\n\n218,356                                \n\n4,225,300\n+1,439\n22,675\n109\n132,594\n6,482\n37,438,974\n1,111,470\n33,684,208 \nSouth America\n\n81541\n\n\n673\n',
 '\n36\nSwitzerland\n4,382,359\n\n14,388                                \n\n4,331,160\n+5,197\n36,811\n63\n499,492\n1,640\n23,292,004\n2,654,772\n8,773,637 \nEurope\n\n26100\n\n\n4,196\n',
 '\n37\nPhilippines\n4,067,170\n\n65,464                                \n\n3,989,188\n\n12,518\n162\n36,150\n582\n34,073,949\n302,855\n112,508,994 \nAsia\n\n281,7193\n\n\n111\n',
 '\n38\nSouth Africa\n4,050,050\n\n102,568                                \n\n3,912,506\n\n34,976\n192\n66,661\n1,688\n26,473,049\n435,726\n60,756,135 \nAfrica\n\n155922\n\n\n576\n',
 '\n39\nRomania\n3,312,085\n\n67,408                                \n\n3,237,640\n\n7,037\n110\n174,033\n3,542\n26,082,014\n1,370,477\n19,031,335 \nEurope\n\n62821\n\n\n370\n',
 '\n40\nDenmark\n3,169,858\n\n7,889                                \n\n3,154,368\n\n7,601\n17\n543,254\n1,352\n129,060,758\n22,118,571\n5,834,950 \nEurope\n\n27400\n\n\n1,303\n',
 '\n41\nHong Kong\n2,755,827\n\n12,276                                \n\n2,126,102\n\n617,449\n54\n362,404\n1,614\n75,375,235\n9,912,187\n7,604,299 \nAsia\n\n36190\n\n\n81,197\n',
 '\n42\nSweden\n2,683,356\n\n22,110                                \n\n2,619,890\n+1,628\n41,356\n43\n262,586\n2,164\n19,333,094\n1,891,883\n10,218,971 \nEurope\n\n44621\n\n\n4,047\n',
 '\n43\nIraq\n2,465,545\n\n25,375                                \n\n2,439,497\n\n673\n21\n58,474\n602\n19,544,451\n463,523\n42,164,965 \nAsia\n\n171,6622\n\n\n16\n',
 '\n44\nSerbia\n2,452,493\n\n17,558                                \n\n2,418,818\n\n16,117\n24\n283,426\n2,029\n11,925,792\n1,378,224\n8,653,016 \nEurope\n\n44931\n\n\n1,863\n',
 '\n45\nSingapore\n2,207,670\n\n1,712                                \n\n2,133,654\n\n72,304\n2\n371,440\n288\n24,755,451\n4,165,098\n5,943,546 \nAsia\n\n33,4720\n\n\n12,165\n',
 '\n46\nHungary\n2,188,737\n\n48,546                                \n\n2,127,121\n\n13,070\n16\n227,845\n5,054\n11,394,556\n1,186,160\n9,606,259 \nEurope\n\n41981\n\n\n1,361\n',
 '\n47\nNew Zealand\n2,117,094\n\n3,568                                \n\n2,092,041\n\n21,485\n\n432,219\n728\n7,710,637\n1,574,177\n4,898,203 \nAustralia/Oceania\n\n21,3731\n\n\n4,386\n',
 '\n48\nBangladesh\n2,037,250\n\n29,440                                \n\n1,988,475\n\n19,335\n1,331\n12,135\n175\n15,160,408\n90,302\n167,885,689 \nAsia\n\n825,70311\n\n\n115\n',
 '\n49\nSlovakia\n1,859,692\n+24\n20,845                                \n+4\n1,837,846\n+31\n1,001\n28\n340,591\n3,818\n7,377,939\n1,351,223\n5,460,193 \nEurope\n\n32621\n4\n0.7\n183\n',
 '\n50\nGeorgia\n1,809,359\n\n16,899                                \n\n1,776,548\n\n15,912\n\n455,903\n4,258\n16,920,079\n4,263,340\n3,968,738 \nAsia\n\n22350\n\n\n4,009\n',
 '\n51\nJordan\n1,746,997\n\n14,122                                \n\n1,731,007\n\n1,868\n59\n169,597\n1,371\n17,201,885\n1,669,945\n10,300,869 \nAsia\n\n67291\n\n\n181\n',
 '\n52\nIreland\n1,693,847\n\n8,339                                \n\n1,674,770\n+251\n10,738\n36\n337,406\n1,661\n12,939,937\n2,577,575\n5,020,199 \nEurope\n\n36020\n\n\n2,139\n',
 '\n53\nPakistan\n1,575,953\n+18\n30,638                                \n\n1,538,689\n\n6,626\n22\n6,867\n134\n30,570,862\n133,213\n229,488,994 \nAsia\n\n1467,4908\n0.08\n\n29\n',
 '\n54\nNorway\n1,476,206\n\n4,571                                \n\n1,468,933\n\n2,702\n20\n267,847\n829\n11,002,430\n1,996,315\n5,511,370 \nEurope\n\n41,2061\n\n\n490\n',
 '\n55\nFinland\n1,446,397\n\n8,263                                \n\n1,421,408\n+1,580\n16,726\n21\n260,379\n1,487\n11,984,148\n2,157,378\n5,554,960 \nEurope\n\n46720\n\n\n3,011\n',
 '\n56\nKazakhstan\n1,404,104\n+169\n13,695                                \n\n1,383,020\n\n7,389\n24\n73,111\n713\n11,575,012\n602,707\n19,205,043 \nAsia\n\n141,4022\n9\n\n385\n',
 '\n57\nSlovenia\n1,313,501\n\n7,025                                \n\n1,292,579\n\n13,897\n21\n632,088\n3,381\n2,811,092\n1,352,765\n2,078,034 \nEurope\n\n22961\n\n\n6,688\n',
 '\n58\nBulgaria\n1,293,216\n\n38,122                                \n\n1,251,048\n\n4,046\n40\n188,940\n5,570\n10,917,308\n1,595,026\n6,844,597 \nEurope\n\n51801\n\n\n591\n',
 '\n59\nLithuania\n1,290,919\n+27\n9,502                                \n+1\n1,274,028\n+125\n7,389\n8\n484,996\n3,570\n10,324,083\n3,878,744\n2,661,708 \nEurope\n\n22800\n10\n0.4\n2,776\n',
 '\n60\nMorocco\n1,271,868\n\n16,295                                \n\n1,255,219\n\n354\n293\n33,672\n431\n12,876,656\n340,898\n37,772,756 \nAfrica\n\n302,3183\n\n\n9\n',
 '\n61\nCroatia\n1,265,333\n\n17,669                                \n\n1,245,723\n\n1,941\n36\n311,713\n4,353\n5,437,406\n1,339,498\n4,059,286 \nEurope\n\n32301\n\n\n478\n',
 '\n62\nLebanon\n1,223,536\n\n10,752                                \n\n1,087,587\n\n125,197\n74\n183,031\n1,608\n4,795,578\n717,380\n6,684,849 \nAsia\n\n56221\n\n\n18,728\n',
 '\n63\nGuatemala\n1,211,008\n\n20,017                                \n\n1,174,756\n\n16,235\n5\n65,164\n1,077\n6,587,246\n354,457\n18,584,039 \nNorth America\n\n159283\n\n\n874\n',
 '\n64\nCosta Rica\n1,171,802\n\n9,104                                \n\n860,711\n\n301,987\n52\n226,114\n1,757\n4,659,757\n899,158\n5,182,354 \nNorth America\n\n45691\n\n\n58,272\n',
 '\n65\nBolivia\n1,168,711\n\n22,315                                \n\n1,113,655\n\n32,741\n220\n97,452\n1,861\n2,705,422\n225,590\n11,992,656 \nSouth America\n\n105374\n\n\n2,730\n',
 '\n66\nTunisia\n1,147,645\n\n29,285                                \n\nN/A\nN/A\nN/A\n44\n95,267\n2,431\n4,985,258\n413,829\n12,046,656 \nAfrica\n\n104112\n\n\n694\n',
 '\n67\nCuba\n1,112,134\n\n8,530                                \n\n1,103,455\n\n149\n23\n98,370\n754\n14,276,770\n1,262,799\n11,305,652 \nNorth America\n\n101,3251\n\n\n13\n',
 '\n68\nUAE\n1,047,371\n\n2,348                                \n\n1,030,367\n\n14,656\n\n103,887\n233\n198,071,556\n19,646,477\n10,081,785 \nAsia\n\n104,2940\n\n\n1,454\n',
 '\n69\nEcuador\n1,040,463\n\n35,940                                \n\n1,000,080\n+1,110\n4,443\n759\n57,442\n1,984\n3,082,403\n170,173\n18,113,361 \nSouth America\n\n175046\n\n\n245\n',
 '\n70\nPanama\n1,025,844\n\n8,575                                \n\n1,014,270\n\n2,999\n16\n230,684\n1,928\n7,404,783\n1,665,132\n4,446,964 \nNorth America\n\n45191\n\n\n674\n',
 '\n71\nUruguay\n1,020,161\n\n7,570                                \n\n1,004,306\n\n8,285\n18\n291,807\n2,165\n6,114,822\n1,749,083\n3,496,016 \nSouth America\n\n34621\n\n\n2,370\n',
 '\n72\nMongolia\n1,007,765\n\n2,179                                \n\n1,005,087\n\n499\n192\n298,325\n645\n4,030,048\n1,193,000\n3,378,078 \nAsia\n\n31,5501\n\n\n148\n',
 '\n73\nNepal\n1,001,020\n\n12,020                                \n\n988,979\n\n21\n\n33,118\n398\n5,992,656\n198,264\n30,225,582 \nAsia\n\n302,5155\n\n\n0.7\n',
 '\n74\nBelarus\n994,037\n\n7,118                                \n\n985,592\n\n1,327\n\n105,381\n755\n13,646,641\n1,446,722\n9,432,800 \nEurope\n\n91,3251\n\n\n141\n',
 '\n75\nLatvia\n974,574\n\n6,177                                \n\n966,418\n\n1,979\n13\n527,128\n3,341\n7,851,262\n4,246,595\n1,848,837 \nEurope\n\n22990\n\n\n1,070\n',
 '\n76\nSaudi Arabia\n827,190\n\n9,529                                \n\n814,821\n\n2,840\n18\n23,077\n266\n44,963,615\n1,254,393\n35,844,909 \nAsia\n\n433,7621\n\n\n79\n',
 '\n77\nAzerbaijan\n826,803\n\n10,017                                \n\n816,382\n\n404\n\n80,271\n973\n7,441,759\n722,486\n10,300,205 \nAsia\n\n121,0281\n\n\n39\n',
 '\n78\nParaguay\n798,231\n\n19,716                                \n\nN/A\nN/A\nN/A\n7\n109,259\n2,699\n2,657,506\n363,751\n7,305,843 \nSouth America\n\n93713\n\n\n10,977\n',
 '\n79\nBahrain\n699,137\n\n1,539                                \n\n697,064\n\n534\n11\n391,897\n863\n10,645,441\n5,967,232\n1,783,983 \nAsia\n\n31,1590\n\n\n299\n',
 '\n80\nSri Lanka\n671,927\n\n16,818                                \n\n655,072\n\n37\n\n31,143\n779\n6,486,117\n300,619\n21,575,842 \nAsia\n\n321,2833\n\n\n2\n',
 '\n81\nKuwait\n662,747\n\n2,570                                \n\n660,095\n\n82\n\n151,301\n587\n8,447,300\n1,928,464\n4,380,326 \nAsia\n\n71,7041\n\n\n19\n',
 '\n82\nDominican Republic\n650,990\n\n4,384                                \n\n644,785\n\n1,821\n4\n58,879\n397\n3,740,928\n338,350\n11,056,370 \nNorth America\n\n172,5223\n\n\n165\n',
 '\n83\nCyprus\n634,709\n\n1,262                                \n\n624,300\n\n9,147\n60\n518,813\n1,032\n9,640,118\n7,879,860\n1,223,387 \nAsia\n\n29690\n\n\n7,477\n',
 '\n84\nMyanmar\n633,713\n\n19,490                                \n\n608,346\n\n5,877\n\n11,475\n353\n9,845,419\n178,271\n55,227,143 \nAsia\n\n872,8346\n\n\n106\n',
 '\n85\nPalestine\n621,008\n\n5,404                                \n\n615,445\n\n159\n17\n116,173\n1,011\n3,078,533\n575,907\n5,345,541 \nAsia\n\n99892\n\n\n30\n',
 '\n86\nEstonia\n612,432\n\n2,872                                \n\n524,990\n\n84,570\n11\n463,293\n2,173\n3,638,453\n2,752,421\n1,321,910 \nEurope\n\n24600\n\n\n63,976\n',
 '\n87\nMoldova\n596,914\n\n11,936                                \n\n504,142\n\n80,836\n49\n148,739\n2,974\n3,216,305\n801,437\n4,013,171 \nEurope\n\n73361\n\n\n20,143\n',
 '\n88\nVenezuela\n550,740\n\n5,834                                \n\n543,956\n\n950\n36\n18,818\n199\n3,359,014\n114,771\n29,266,991 \nSouth America\n\n535,0179\n\n\n32\n',
 '\n89\nEgypt\n515,645\n\n24,613                                \n\n442,182\n\n48,850\n122\n4,857\n232\n3,693,367\n34,792\n106,156,692 \nAfrica\n\n2064,31329\n\n\n460\n',
 '\n90\nLibya\n507,153\n\n6,437                                \n\n500,675\n\n41\n\n72,031\n914\n2,483,446\n352,725\n7,040,745 \nAfrica\n\n141,0943\n\n\n6\n',
 '\n91\nEthiopia\n498,660\n\n7,572                                \n\n482,606\n\n8,482\n\n4,128\n63\n5,431,905\n44,961\n120,812,698 \nAfrica\n\n24215,95522\n\n\n70\n',
 '\n92\nQatar\n490,493\n\n685                                \n\n489,258\n\n550\n1\n164,600\n230\n4,065,369\n1,364,257\n2,979,915 \nAsia\n\n64,3501\n\n\n185\n',
 '\n93\nRéunion\n480,501\n\n907                                \n\n418,572\n\n61,022\n10\n529,151\n999\n1,603,660\n1,766,027\n908,061 \nAfrica\n\n21,0011\n\n\n67,200\n',
 '\n94\nHonduras\n468,048\n\n11,088                                \n\nN/A\nN/A\nN/A\n105\n45,792\n1,085\n1,602,425\n156,774\n10,221,247 \nNorth America\n\n229226\n\n\n31,739\n',
 '\n95\nArmenia\n445,976\n\n8,716                                \n\n435,162\n\n2,098\n\n150,061\n2,933\n3,242,901\n1,091,164\n2,971,966 \nAsia\n\n73411\n\n\n706\n',
 '\n96\nBosnia and Herzegovina\n401,083\n\n16,234                                \n\n378,846\n\n6,003\n\n123,436\n4,996\n1,882,568\n579,373\n3,249,317 \nEurope\n\n82002\n\n\n1,847\n',
 '\n97\nOman\n399,154\n\n4,260                                \n\n384,669\n\n10,225\n2\n74,973\n800\n25,000,000\n4,695,724\n5,323,993 \nAsia\n\n131,2500\n\n\n1,921\n',
 '\n98\nNorth Macedonia\n345,857\n\n9,614                                \n\n335,979\n\n264\n\n166,173\n4,619\n2,208,755\n1,061,236\n2,081,304 \nEurope\n\n62161\n\n\n127\n',
 '\n99\nKenya\n342,598\n\n5,688                                \n\n336,791\n\n119\n1\n6,094\n101\n3,960,657\n70,455\n56,215,221 \nAfrica\n\n1649,88314\n\n\n2\n',
 '\n100\nZambia\n335,545\n\n4,028                                \n\n330,301\n\n1,216\n\n17,234\n207\n3,797,662\n195,050\n19,470,234 \nAfrica\n\n584,8345\n\n\n62\n',
 '\n101\nAlbania\n333,916\n\n3,595                                \n\n328,670\n\n1,651\n\n116,494\n1,254\n1,941,032\n677,173\n2,866,374 \nEurope\n\n97971\n\n\n576\n',
 '\n102\nBotswana\n328,071\n\n2,794                                \n\n323,747\n\n1,530\n1\n134,391\n1,145\n2,026,898\n830,300\n2,441,162 \nAfrica\n\n78741\n\n\n627\n',
 '\n103\nLuxembourg\n297,757\n\n1,133                                \n\n288,991\n\n7,633\n\n463,528\n1,764\n4,412,567\n6,869,188\n642,371 \nEurope\n\n25670\n\n\n11,883\n',
 '\n104\nMontenegro\n285,031\n\n2,791                                \n\n281,852\n\n388\n6\n453,907\n4,445\n2,681,486\n4,270,222\n627,950 \nEurope\n\n22250\n\n\n618\n',

In [8]:
list_data =[]
for tag in tags:
    list_data.append(tag.text.split('\n'))
    
    
list_data

[['',
  '#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop',
  ''],
 ['',
  '',
  '',
  'North America',
  '',
  '122,004,226',
  '',
  '1,582,327',
  '',
  '116,661,411',
  '+2,541',
  '3,760,488',
  '10,260',
  '',
  '',
  '',
  '',
  '',
  'North America',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'Asia',
  '',
  '209,278,066',
  '+260,914',
  '1,516,422',
  '+477',
  '194,552,674',
  '+109,061',
  '13,208,970',
  '16,218',
  '',
  '',
  '',
  '',
  '',
  'Asia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'Europe',
  '',
  '243,620,216',
  '+3,402',
  '1,989,034',
  '+51',
  '238,230,364',
  '+20,262',
  '3,400,818',
  '7,429',
  '',
  '',
  '',
  '',
  '',
  'Europe',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'South America',
  '',
  '67,175,673',
  '',
  '1,343,494',
  '',
  '64,761,096',
  '+2,549',
  '1,071,083',
  '10,330',
  '',
  '',
  '',
  '',
  '',
  'South America',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'Oceania',
  '',
  '13,730,218',
  '',
  '23,701',
  '',
  '13,450,170',
  '',
  '256,347',
  '157',
  '',
  '',
  '',
  '',
  '',
  'Australia/Oceania',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  'Africa',
  '',
  '12,745,763',
  '',
  '258,374',
  '',
  '12,042,984',
  '',
  '444,405',
  '837',
  '',
  '',
  '',
  '',
  '',
  'Africa',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  '',
  '',
  '721',
  '',
  '15',
  '',
  '706',
  '',
  '0',
  '0',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'World',
  '668,554,883',
  '+264,316',
  '6,713,367',
  '+528',
  '639,699,405',
  '+134,413',
  '22,142,111',
  '45,231',
  '85,769',
  '861.3',
  '',
  '',
  '',
  'All',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '1',
  'USA',
  '103,081,401',
  '',
  '1,121,089                                ',
  '',
  '99,876,630',
  '',
  '2,083,682',
  '5,077',
  '307,885',
  '3,348',
  '1,155,402,577',
  '3,450,969',
  '334,805,269 ',
  'North America',
  '',
  '32990',
  '',
  '',
  '6,224',
  ''],
 ['',
  '2',
  'India',
  '44,681,017',
  '',
  '530,720                                ',
  '',
  '44,146,781',
  '',
  '3,516',
  '698',
  '31,765',
  '377',
  '911,951,216',
  '648,323',
  '1,406,631,776 ',
  'Asia',
  '',
  '312,6502',
  '',
  '',
  '2',
  ''],
 ['',
  '3',
  'France',
  '39,401,170',
  '',
  '162,643                                ',
  '',
  '38,729,049',
  '',
  '509,478',
  '869',
  '600,769',
  '2,480',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '',
  '24030',
  '',
  '',
  '7,768',
  ''],
 ['',
  '4',
  'Germany',
  '37,509,539',
  '',
  '162,688                                ',
  '',
  '36,831,800',
  '+5,900',
  '515,051',
  '1,406',
  '447,162',
  '1,939',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '',
  '25161',
  '',
  '',
  '6,140',
  ''],
 ['',
  '5',
  'Brazil',
  '36,500,341',
  '',
  '694,900                                ',
  '',
  '35,247,755',
  '',
  '557,686',
  '8,318',
  '169,490',
  '3,227',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '',
  '63103',
  '',
  '',
  '2,590',
  ''],
 ['',
  '6',
  'Japan',
  '30,473,569',
  '+190,538',
  '59,822                                ',
  '+407',
  '21,257,687',
  '+10,719',
  '9,156,060',
  '671',
  '242,653',
  '476',
  '87,294,964',
  '695,108',
  '125,584,838 ',
  'Asia',
  '',
  '42,0991',
  '1,517',
  '3',
  '72,907',
  ''],
 ['',
  '7',
  'S. Korea',
  '29,520,600',
  '+46,766',
  '32,590                                ',
  '+34',
  '28,358,090',
  '+88,112',
  '1,129,920',
  '526',
  '575,115',
  '635',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '',
  '21,5753',
  '911',
  '0.7',
  '22,013',
  ''],
 ['',
  '8',
  'Italy',
  '25,279,682',
  '',
  '185,417                                ',
  '',
  '24,688,083',
  '',
  '406,182',
  '319',
  '419,491',
  '3,077',
  '263,414,564',
  '4,371,100',
  '60,262,770 ',
  'Europe',
  '',
  '23250',
  '',
  '',
  '6,740',
  ''],
 ['',
  '9',
  'UK',
  '24,210,131',
  '',
  '201,028                                ',
  '',
  '23,874,846',
  '',
  '134,257',
  '146',
  '353,443',
  '2,935',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '',
  '33410',
  '',
  '',
  '1,960',
  ''],
 ['',
  '10',
  'Russia',
  '21,826,982',
  '+3,127',
  '394,080                                ',
  '+45',
  '21,245,559',
  '+3,694',
  '187,343',
  '2,300',
  '149,699',
  '2,703',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '',
  '73701',
  '21',
  '0.3',
  '1,285',
  ''],
 ['',
  '11',
  'Turkey',
  '17,042,722',
  '',
  '101,492                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '199,186',
  '1,186',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '',
  '58431',
  '',
  '',
  '1,819',
  ''],
 ['',
  '12',
  'Spain',
  '13,693,478',
  '',
  '117,413                                ',
  '',
  '13,502,806',
  '',
  '73,259',
  '231',
  '293,102',
  '2,513',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '',
  '33980',
  '',
  '',
  '1,568',
  ''],
 ['',
  '13',
  'Vietnam',
  '11,525,711',
  '',
  '43,186                                ',
  '',
  '10,611,494',
  '',
  '871,031',
  '23',
  '116,476',
  '436',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '',
  '92,2911',
  '',
  '',
  '8,802',
  ''],
 ['',
  '14',
  'Australia',
  '11,205,520',
  '',
  '17,304                                ',
  '',
  '11,052,693',
  '',
  '135,523',
  '124',
  '429,844',
  '664',
  '78,835,048',
  '3,024,116',
  '26,068,792 ',
  'Australia/Oceania',
  '',
  '21,5070',
  '',
  '',
  '5,199',
  ''],
 ['',
  '15',
  'Argentina',
  '9,963,697',
  '',
  '130,171                                ',
  '',
  '9,636,804',
  '',
  '196,722',
  '402',
  '216,554',
  '2,829',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '',
  '53531',
  '',
  '',
  '4,276',
  ''],
 ['',
  '16',
  'Taiwan',
  '9,055,191',
  '+23,411',
  '15,542                                ',
  '+36',
  '8,572,902',
  '+10,298',
  '466,747',
  '',
  '379,059',
  '651',
  '29,524,201',
  '1,235,912',
  '23,888,595 ',
  'Asia',
  '',
  '31,5371',
  '980',
  '2',
  '19,538',
  ''],
 ['',
  '17',
  'Netherlands',
  '8,574,631',
  '',
  '22,989                                ',
  '',
  '8,526,387',
  '+1,126',
  '25,255',
  '55',
  '498,193',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '',
  '27491',
  '',
  '',
  '1,467',
  ''],
 ['',
  '18',
  'Iran',
  '7,561,808',
  '',
  '144,706                                ',
  '',
  '7,336,407',
  '',
  '80,695',
  '153',
  '87,905',
  '1,682',
  '54,420,785',
  '632,632',
  '86,022,837 ',
  'Asia',
  '',
  '115942',
  '',
  '',
  '938',
  ''],
 ['',
  '19',
  'Mexico',
  '7,271,010',
  '',
  '331,263                                ',
  '',
  '6,503,502',
  '',
  '436,245',
  '4,798',
  '55,266',
  '2,518',
  '19,042,684',
  '144,742',
  '131,562,772 ',
  'North America',
  '',
  '183977',
  '',
  '',
  '3,316',
  ''],
 ['',
  '20',
  'Indonesia',
  '6,723,201',
  '',
  '160,679                                ',
  '',
  '6,554,066',
  '',
  '8,456',
  '2,771',
  '24,086',
  '576',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '',
  '421,7372',
  '',
  '',
  '30',
  ''],
 ['',
  '21',
  'Poland',
  '6,371,259',
  '+143',
  '118,586                                ',
  '',
  '5,335,940',
  '',
  '916,733',
  '1,192',
  '168,821',
  '3,142',
  '38,021,654',
  '1,007,469',
  '37,739,785 ',
  'Europe',
  '',
  '63181',
  '4',
  '',
  '24,291',
  ''],
 ['',
  '22',
  'Colombia',
  '6,349,971',
  '',
  '142,259                                ',
  '',
  '6,170,360',
  '',
  '37,352',
  '342',
  '123,270',
  '2,762',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '',
  '83621',
  '',
  '',
  '725',
  ''],
 ['',
  '23',
  'Austria',
  '5,724,215',
  '',
  '21,484                                ',
  '',
  '5,666,495',
  '',
  '36,236',
  '',
  '631,344',
  '2,370',
  '204,767,733',
  '22,584,568',
  '9,066,710 ',
  'Europe',
  '',
  '24220',
  '',
  '',
  '3,997',
  ''],
 ['',
  '24',
  'Portugal',
  '5,557,941',
  '',
  '25,805                                ',
  '',
  '5,523,729',
  '+289',
  '8,407',
  '61',
  '548,090',
  '2,545',
  '45,826,501',
  '4,519,125',
  '10,140,570 ',
  'Europe',
  '',
  '23930',
  '',
  '',
  '829',
  ''],
 ['',
  '25',
  'Greece',
  '5,548,487',
  '',
  '34,779                                ',
  '',
  '5,513,708',
  '',
  '0',
  '115',
  '537,819',
  '3,371',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '',
  '22970',
  '',
  '',
  '',
  ''],
 ['',
  '26',
  'Ukraine',
  '5,361,352',
  '',
  '110,859                                ',
  '',
  '5,242,011',
  '+576',
  '8,482',
  '',
  '124,128',
  '2,567',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '',
  '83901',
  '',
  '',
  '196',
  ''],
 ['',
  '27',
  'Chile',
  '5,062,734',
  '',
  '63,330                                ',
  '',
  '4,986,896',
  '',
  '12,508',
  '113',
  '262,997',
  '3,290',
  '47,804,159',
  '2,483,308',
  '19,250,195 ',
  'South America',
  '',
  '43040',
  '',
  '',
  '650',
  ''],
 ['',
  '28',
  'Malaysia',
  '5,029,908',
  '',
  '36,874                                ',
  '',
  '4,981,603',
  '',
  '11,431',
  '34',
  '151,590',
  '1,111',
  '67,275,350',
  '2,027,522',
  '33,181,072 ',
  'Asia',
  '',
  '79000',
  '',
  '',
  '345',
  ''],
 ['',
  '29',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '',
  '5351,225',
  '',
  '',
  '',
  ''],
 ['',
  '30',
  'Israel',
  '4,770,244',
  '',
  '12,079                                ',
  '',
  '4,748,068',
  '',
  '10,097',
  '57',
  '511,499',
  '1,295',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '',
  '27720',
  '',
  '',
  '1,083',
  ''],
 ['',
  '31',
  'Thailand',
  '4,723,919',
  '',
  '33,669                                ',
  '',
  '4,690,108',
  '',
  '142',
  '1,496',
  '67,409',
  '480',
  '17,270,775',
  '246,450',
  '70,078,203 ',
  'Asia',
  '',
  '152,0814',
  '',
  '',
  '2',
  ''],
 ['',
  '32',
  'Belgium',
  '4,682,234',
  '',
  '33,395                                ',
  '',
  '4,614,647',
  '+1,188',
  '34,192',
  '97',
  '401,279',
  '2,862',
  '36,436,600',
  '3,122,706',
  '11,668,278 ',
  'Europe',
  '',
  '23490',
  '',
  '',
  '2,930',
  ''],
 ['',
  '33',
  'Czechia',
  '4,582,935',
  '+81',
  '42,200                                ',
  '+1',
  '4,535,854',
  '+536',
  '4,881',
  '43',
  '426,844',
  '3,930',
  '56,812,823',
  '5,291,419',
  '10,736,784 ',
  'Europe',
  '',
  '22540',
  '8',
  '0.09',
  '455',
  ''],
 ['',
  '34',
  'Canada',
  '4,475,268',
  '',
  '48,948                                ',
  '',
  '4,386,809',
  '+2,541',
  '39,511',
  '99',
  '116,579',
  '1,275',
  '66,343,123',
  '1,728,207',
  '38,388,419 ',
  'North America',
  '',
  '97841',
  '',
  '',
  '1,029',
  ''],
 ['',
  '35',
  'Peru',
  '4,466,331',
  '',
  '218,356                                ',
  '',
  '4,225,300',
  '+1,439',
  '22,675',
  '109',
  '132,594',
  '6,482',
  '37,438,974',
  '1,111,470',
  '33,684,208 ',
  'South America',
  '',
  '81541',
  '',
  '',
  '673',
  ''],
 ['',
  '36',
  'Switzerland',
  '4,382,359',
  '',
  '14,388                                ',
  '',
  '4,331,160',
  '+5,197',
  '36,811',
  '63',
  '499,492',
  '1,640',
  '23,292,004',
  '2,654,772',
  '8,773,637 ',
  'Europe',
  '',
  '26100',
  '',
  '',
  '4,196',
  ''],
 ['',
  '37',
  'Philippines',
  '4,067,170',
  '',
  '65,464                                ',
  '',
  '3,989,188',
  '',
  '12,518',
  '162',
  '36,150',
  '582',
  '34,073,949',
  '302,855',
  '112,508,994 ',
  'Asia',
  '',
  '281,7193',
  '',
  '',
  '111',
  ''],
 ['',
  '38',
  'South Africa',
  '4,050,050',
  '',
  '102,568                                ',
  '',
  '3,912,506',
  '',
  '34,976',
  '192',
  '66,661',
  '1,688',
  '26,473,049',
  '435,726',
  '60,756,135 ',
  'Africa',
  '',
  '155922',
  '',
  '',
  '576',
  ''],
 ['',
  '39',
  'Romania',
  '3,312,085',
  '',
  '67,408                                ',
  '',
  '3,237,640',
  '',
  '7,037',
  '110',
  '174,033',
  '3,542',
  '26,082,014',
  '1,370,477',
  '19,031,335 ',
  'Europe',
  '',
  '62821',
  '',
  '',
  '370',
  ''],
 ['',
  '40',
  'Denmark',
  '3,169,858',
  '',
  '7,889                                ',
  '',
  '3,154,368',
  '',
  '7,601',
  '17',
  '543,254',
  '1,352',
  '129,060,758',
  '22,118,571',
  '5,834,950 ',
  'Europe',
  '',
  '27400',
  '',
  '',
  '1,303',
  ''],
 ['',
  '41',
  'Hong Kong',
  '2,755,827',
  '',
  '12,276                                ',
  '',
  '2,126,102',
  '',
  '617,449',
  '54',
  '362,404',
  '1,614',
  '75,375,235',
  '9,912,187',
  '7,604,299 ',
  'Asia',
  '',
  '36190',
  '',
  '',
  '81,197',
  ''],
 ['',
  '42',
  'Sweden',
  '2,683,356',
  '',
  '22,110                                ',
  '',
  '2,619,890',
  '+1,628',
  '41,356',
  '43',
  '262,586',
  '2,164',
  '19,333,094',
  '1,891,883',
  '10,218,971 ',
  'Europe',
  '',
  '44621',
  '',
  '',
  '4,047',
  ''],
 ['',
  '43',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '21',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '',
  '171,6622',
  '',
  '',
  '16',
  ''],
 ['',
  '44',
  'Serbia',
  '2,452,493',
  '',
  '17,558                                ',
  '',
  '2,418,818',
  '',
  '16,117',
  '24',
  '283,426',
  '2,029',
  '11,925,792',
  '1,378,224',
  '8,653,016 ',
  'Europe',
  '',
  '44931',
  '',
  '',
  '1,863',
  ''],
 ['',
  '45',
  'Singapore',
  '2,207,670',
  '',
  '1,712                                ',
  '',
  '2,133,654',
  '',
  '72,304',
  '2',
  '371,440',
  '288',
  '24,755,451',
  '4,165,098',
  '5,943,546 ',
  'Asia',
  '',
  '33,4720',
  '',
  '',
  '12,165',
  ''],
 ['',
  '46',
  'Hungary',
  '2,188,737',
  '',
  '48,546                                ',
  '',
  '2,127,121',
  '',
  '13,070',
  '16',
  '227,845',
  '5,054',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '',
  '41981',
  '',
  '',
  '1,361',
  ''],
 ['',
  '47',
  'New Zealand',
  '2,117,094',
  '',
  '3,568                                ',
  '',
  '2,092,041',
  '',
  '21,485',
  '',
  '432,219',
  '728',
  '7,710,637',
  '1,574,177',
  '4,898,203 ',
  'Australia/Oceania',
  '',
  '21,3731',
  '',
  '',
  '4,386',
  ''],
 ['',
  '48',
  'Bangladesh',
  '2,037,250',
  '',
  '29,440                                ',
  '',
  '1,988,475',
  '',
  '19,335',
  '1,331',
  '12,135',
  '175',
  '15,160,408',
  '90,302',
  '167,885,689 ',
  'Asia',
  '',
  '825,70311',
  '',
  '',
  '115',
  ''],
 ['',
  '49',
  'Slovakia',
  '1,859,692',
  '+24',
  '20,845                                ',
  '+4',
  '1,837,846',
  '+31',
  '1,001',
  '28',
  '340,591',
  '3,818',
  '7,377,939',
  '1,351,223',
  '5,460,193 ',
  'Europe',
  '',
  '32621',
  '4',
  '0.7',
  '183',
  ''],
 ['',
  '50',
  'Georgia',
  '1,809,359',
  '',
  '16,899                                ',
  '',
  '1,776,548',
  '',
  '15,912',
  '',
  '455,903',
  '4,258',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '',
  '22350',
  '',
  '',
  '4,009',
  ''],
 ['',
  '51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '',
  '67291',
  '',
  '',
  '181',
  ''],
 ['',
  '52',
  'Ireland',
  '1,693,847',
  '',
  '8,339                                ',
  '',
  '1,674,770',
  '+251',
  '10,738',
  '36',
  '337,406',
  '1,661',
  '12,939,937',
  '2,577,575',
  '5,020,199 ',
  'Europe',
  '',
  '36020',
  '',
  '',
  '2,139',
  ''],
 ['',
  '53',
  'Pakistan',
  '1,575,953',
  '+18',
  '30,638                                ',
  '',
  '1,538,689',
  '',
  '6,626',
  '22',
  '6,867',
  '134',
  '30,570,862',
  '133,213',
  '229,488,994 ',
  'Asia',
  '',
  '1467,4908',
  '0.08',
  '',
  '29',
  ''],
 ['',
  '54',
  'Norway',
  '1,476,206',
  '',
  '4,571                                ',
  '',
  '1,468,933',
  '',
  '2,702',
  '20',
  '267,847',
  '829',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '',
  '41,2061',
  '',
  '',
  '490',
  ''],
 ['',
  '55',
  'Finland',
  '1,446,397',
  '',
  '8,263                                ',
  '',
  '1,421,408',
  '+1,580',
  '16,726',
  '21',
  '260,379',
  '1,487',
  '11,984,148',
  '2,157,378',
  '5,554,960 ',
  'Europe',
  '',
  '46720',
  '',
  '',
  '3,011',
  ''],
 ['',
  '56',
  'Kazakhstan',
  '1,404,104',
  '+169',
  '13,695                                ',
  '',
  '1,383,020',
  '',
  '7,389',
  '24',
  '73,111',
  '713',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '',
  '141,4022',
  '9',
  '',
  '385',
  ''],
 ['',
  '57',
  'Slovenia',
  '1,313,501',
  '',
  '7,025                                ',
  '',
  '1,292,579',
  '',
  '13,897',
  '21',
  '632,088',
  '3,381',
  '2,811,092',
  '1,352,765',
  '2,078,034 ',
  'Europe',
  '',
  '22961',
  '',
  '',
  '6,688',
  ''],
 ['',
  '58',
  'Bulgaria',
  '1,293,216',
  '',
  '38,122                                ',
  '',
  '1,251,048',
  '',
  '4,046',
  '40',
  '188,940',
  '5,570',
  '10,917,308',
  '1,595,026',
  '6,844,597 ',
  'Europe',
  '',
  '51801',
  '',
  '',
  '591',
  ''],
 ['',
  '59',
  'Lithuania',
  '1,290,919',
  '+27',
  '9,502                                ',
  '+1',
  '1,274,028',
  '+125',
  '7,389',
  '8',
  '484,996',
  '3,570',
  '10,324,083',
  '3,878,744',
  '2,661,708 ',
  'Europe',
  '',
  '22800',
  '10',
  '0.4',
  '2,776',
  ''],
 ['',
  '60',
  'Morocco',
  '1,271,868',
  '',
  '16,295                                ',
  '',
  '1,255,219',
  '',
  '354',
  '293',
  '33,672',
  '431',
  '12,876,656',
  '340,898',
  '37,772,756 ',
  'Africa',
  '',
  '302,3183',
  '',
  '',
  '9',
  ''],
 ['',
  '61',
  'Croatia',
  '1,265,333',
  '',
  '17,669                                ',
  '',
  '1,245,723',
  '',
  '1,941',
  '36',
  '311,713',
  '4,353',
  '5,437,406',
  '1,339,498',
  '4,059,286 ',
  'Europe',
  '',
  '32301',
  '',
  '',
  '478',
  ''],
 ['',
  '62',
  'Lebanon',
  '1,223,536',
  '',
  '10,752                                ',
  '',
  '1,087,587',
  '',
  '125,197',
  '74',
  '183,031',
  '1,608',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '',
  '56221',
  '',
  '',
  '18,728',
  ''],
 ['',
  '63',
  'Guatemala',
  '1,211,008',
  '',
  '20,017                                ',
  '',
  '1,174,756',
  '',
  '16,235',
  '5',
  '65,164',
  '1,077',
  '6,587,246',
  '354,457',
  '18,584,039 ',
  'North America',
  '',
  '159283',
  '',
  '',
  '874',
  ''],
 ['',
  '64',
  'Costa Rica',
  '1,171,802',
  '',
  '9,104                                ',
  '',
  '860,711',
  '',
  '301,987',
  '52',
  '226,114',
  '1,757',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '',
  '45691',
  '',
  '',
  '58,272',
  ''],
 ['',
  '65',
  'Bolivia',
  '1,168,711',
  '',
  '22,315                                ',
  '',
  '1,113,655',
  '',
  '32,741',
  '220',
  '97,452',
  '1,861',

In [9]:
import csv
file = open('covid.csv','w')
x = csv.writer(file)
x.writerows(list_data)

In [11]:
pwd

'C:\\Users\\user\\Desktop\\python basic'

In [10]:
import pandas as pd
df = pd.read_csv('covid.csv')
df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 123: invalid start byte

In [13]:
tags = table_code.find_all('tr')

In [16]:
list_data =[]
for tag in tags:
    x = tag.text.split('\n')
    if x[1] != '':
        list_data.append(x[1:])
    
    
list_data

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop',
  ''],
 ['1',
  'USA',
  '103,081,401',
  '',
  '1,121,089                                ',
  '',
  '99,876,630',
  '',
  '2,083,682',
  '5,077',
  '307,885',
  '3,348',
  '1,155,402,577',
  '3,450,969',
  '334,805,269 ',
  'North America',
  '',
  '32990',
  '',
  '',
  '6,224',
  ''],
 ['2',
  'India',
  '44,681,017',
  '',
  '530,720                                ',
  '',
  '44,146,781',
  '',
  '3,516',
  '698',
  '31,765',
  '377',
  '911,951,216',
  '648,323',
  '1,406,631,776 ',
  'Asia',
  '',
  '312,6502',
  '',
  '',
  '2',
  ''],
 ['3',
  'France',
  '39,401,170',
  '',
  '162,643                                ',
  '',
  '38,729,049',
  '',
  '509,478',
  '869',
  '600,769',
  '2,480',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '',
  '24030',
  '',
  '',
  '7,768',
  ''],
 ['4',
  'Germany',
  '37,509,539',
  '',
  '162,688                                ',
  '',
  '36,831,800',
  '+5,900',
  '515,051',
  '1,406',
  '447,162',
  '1,939',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '',
  '25161',
  '',
  '',
  '6,140',
  ''],
 ['5',
  'Brazil',
  '36,500,341',
  '',
  '694,900                                ',
  '',
  '35,247,755',
  '',
  '557,686',
  '8,318',
  '169,490',
  '3,227',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '',
  '63103',
  '',
  '',
  '2,590',
  ''],
 ['6',
  'Japan',
  '30,473,569',
  '+190,538',
  '59,822                                ',
  '+407',
  '21,257,687',
  '+10,719',
  '9,156,060',
  '671',
  '242,653',
  '476',
  '87,294,964',
  '695,108',
  '125,584,838 ',
  'Asia',
  '',
  '42,0991',
  '1,517',
  '3',
  '72,907',
  ''],
 ['7',
  'S. Korea',
  '29,520,600',
  '+46,766',
  '32,590                                ',
  '+34',
  '28,358,090',
  '+88,112',
  '1,129,920',
  '526',
  '575,115',
  '635',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '',
  '21,5753',
  '911',
  '0.7',
  '22,013',
  ''],
 ['8',
  'Italy',
  '25,279,682',
  '',
  '185,417                                ',
  '',
  '24,688,083',
  '',
  '406,182',
  '319',
  '419,491',
  '3,077',
  '263,414,564',
  '4,371,100',
  '60,262,770 ',
  'Europe',
  '',
  '23250',
  '',
  '',
  '6,740',
  ''],
 ['9',
  'UK',
  '24,210,131',
  '',
  '201,028                                ',
  '',
  '23,874,846',
  '',
  '134,257',
  '146',
  '353,443',
  '2,935',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '',
  '33410',
  '',
  '',
  '1,960',
  ''],
 ['10',
  'Russia',
  '21,826,982',
  '+3,127',
  '394,080                                ',
  '+45',
  '21,245,559',
  '+3,694',
  '187,343',
  '2,300',
  '149,699',
  '2,703',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '',
  '73701',
  '21',
  '0.3',
  '1,285',
  ''],
 ['11',
  'Turkey',
  '17,042,722',
  '',
  '101,492                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '199,186',
  '1,186',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '',
  '58431',
  '',
  '',
  '1,819',
  ''],
 ['12',
  'Spain',
  '13,693,478',
  '',
  '117,413                                ',
  '',
  '13,502,806',
  '',
  '73,259',
  '231',
  '293,102',
  '2,513',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '',
  '33980',
  '',
  '',
  '1,568',
  ''],
 ['13',
  'Vietnam',
  '11,525,711',
  '',
  '43,186                                ',
  '',
  '10,611,494',
  '',
  '871,031',
  '23',
  '116,476',
  '436',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '',
  '92,2911',
  '',
  '',
  '8,802',
  ''],
 ['14',
  'Australia',
  '11,205,520',
  '',
  '17,304                                ',
  '',
  '11,052,693',
  '',
  '135,523',
  '124',
  '429,844',
  '664',
  '78,835,048',
  '3,024,116',
  '26,068,792 ',
  'Australia/Oceania',
  '',
  '21,5070',
  '',
  '',
  '5,199',
  ''],
 ['15',
  'Argentina',
  '9,963,697',
  '',
  '130,171                                ',
  '',
  '9,636,804',
  '',
  '196,722',
  '402',
  '216,554',
  '2,829',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '',
  '53531',
  '',
  '',
  '4,276',
  ''],
 ['16',
  'Taiwan',
  '9,055,191',
  '+23,411',
  '15,542                                ',
  '+36',
  '8,572,902',
  '+10,298',
  '466,747',
  '',
  '379,059',
  '651',
  '29,524,201',
  '1,235,912',
  '23,888,595 ',
  'Asia',
  '',
  '31,5371',
  '980',
  '2',
  '19,538',
  ''],
 ['17',
  'Netherlands',
  '8,574,631',
  '',
  '22,989                                ',
  '',
  '8,526,387',
  '+1,126',
  '25,255',
  '55',
  '498,193',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '',
  '27491',
  '',
  '',
  '1,467',
  ''],
 ['18',
  'Iran',
  '7,561,808',
  '',
  '144,706                                ',
  '',
  '7,336,407',
  '',
  '80,695',
  '153',
  '87,905',
  '1,682',
  '54,420,785',
  '632,632',
  '86,022,837 ',
  'Asia',
  '',
  '115942',
  '',
  '',
  '938',
  ''],
 ['19',
  'Mexico',
  '7,271,010',
  '',
  '331,263                                ',
  '',
  '6,503,502',
  '',
  '436,245',
  '4,798',
  '55,266',
  '2,518',
  '19,042,684',
  '144,742',
  '131,562,772 ',
  'North America',
  '',
  '183977',
  '',
  '',
  '3,316',
  ''],
 ['20',
  'Indonesia',
  '6,723,201',
  '',
  '160,679                                ',
  '',
  '6,554,066',
  '',
  '8,456',
  '2,771',
  '24,086',
  '576',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '',
  '421,7372',
  '',
  '',
  '30',
  ''],
 ['21',
  'Poland',
  '6,371,259',
  '+143',
  '118,586                                ',
  '',
  '5,335,940',
  '',
  '916,733',
  '1,192',
  '168,821',
  '3,142',
  '38,021,654',
  '1,007,469',
  '37,739,785 ',
  'Europe',
  '',
  '63181',
  '4',
  '',
  '24,291',
  ''],
 ['22',
  'Colombia',
  '6,349,971',
  '',
  '142,259                                ',
  '',
  '6,170,360',
  '',
  '37,352',
  '342',
  '123,270',
  '2,762',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '',
  '83621',
  '',
  '',
  '725',
  ''],
 ['23',
  'Austria',
  '5,724,215',
  '',
  '21,484                                ',
  '',
  '5,666,495',
  '',
  '36,236',
  '',
  '631,344',
  '2,370',
  '204,767,733',
  '22,584,568',
  '9,066,710 ',
  'Europe',
  '',
  '24220',
  '',
  '',
  '3,997',
  ''],
 ['24',
  'Portugal',
  '5,557,941',
  '',
  '25,805                                ',
  '',
  '5,523,729',
  '+289',
  '8,407',
  '61',
  '548,090',
  '2,545',
  '45,826,501',
  '4,519,125',
  '10,140,570 ',
  'Europe',
  '',
  '23930',
  '',
  '',
  '829',
  ''],
 ['25',
  'Greece',
  '5,548,487',
  '',
  '34,779                                ',
  '',
  '5,513,708',
  '',
  '0',
  '115',
  '537,819',
  '3,371',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '',
  '22970',
  '',
  '',
  '',
  ''],
 ['26',
  'Ukraine',
  '5,361,352',
  '',
  '110,859                                ',
  '',
  '5,242,011',
  '+576',
  '8,482',
  '',
  '124,128',
  '2,567',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '',
  '83901',
  '',
  '',
  '196',
  ''],
 ['27',
  'Chile',
  '5,062,734',
  '',
  '63,330                                ',
  '',
  '4,986,896',
  '',
  '12,508',
  '113',
  '262,997',
  '3,290',
  '47,804,159',
  '2,483,308',
  '19,250,195 ',
  'South America',
  '',
  '43040',
  '',
  '',
  '650',
  ''],
 ['28',
  'Malaysia',
  '5,029,908',
  '',
  '36,874                                ',
  '',
  '4,981,603',
  '',
  '11,431',
  '34',
  '151,590',
  '1,111',
  '67,275,350',
  '2,027,522',
  '33,181,072 ',
  'Asia',
  '',
  '79000',
  '',
  '',
  '345',
  ''],
 ['29',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '',
  '5351,225',
  '',
  '',
  '',
  ''],
 ['30',
  'Israel',
  '4,770,244',
  '',
  '12,079                                ',
  '',
  '4,748,068',
  '',
  '10,097',
  '57',
  '511,499',
  '1,295',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '',
  '27720',
  '',
  '',
  '1,083',
  ''],
 ['31',
  'Thailand',
  '4,723,919',
  '',
  '33,669                                ',
  '',
  '4,690,108',
  '',
  '142',
  '1,496',
  '67,409',
  '480',
  '17,270,775',
  '246,450',
  '70,078,203 ',
  'Asia',
  '',
  '152,0814',
  '',
  '',
  '2',
  ''],
 ['32',
  'Belgium',
  '4,682,234',
  '',
  '33,395                                ',
  '',
  '4,614,647',
  '+1,188',
  '34,192',
  '97',
  '401,279',
  '2,862',
  '36,436,600',
  '3,122,706',
  '11,668,278 ',
  'Europe',
  '',
  '23490',
  '',
  '',
  '2,930',
  ''],
 ['33',
  'Czechia',
  '4,582,935',
  '+81',
  '42,200                                ',
  '+1',
  '4,535,854',
  '+536',
  '4,881',
  '43',
  '426,844',
  '3,930',
  '56,812,823',
  '5,291,419',
  '10,736,784 ',
  'Europe',
  '',
  '22540',
  '8',
  '0.09',
  '455',
  ''],
 ['34',
  'Canada',
  '4,475,268',
  '',
  '48,948                                ',
  '',
  '4,386,809',
  '+2,541',
  '39,511',
  '99',
  '116,579',
  '1,275',
  '66,343,123',
  '1,728,207',
  '38,388,419 ',
  'North America',
  '',
  '97841',
  '',
  '',
  '1,029',
  ''],
 ['35',
  'Peru',
  '4,466,331',
  '',
  '218,356                                ',
  '',
  '4,225,300',
  '+1,439',
  '22,675',
  '109',
  '132,594',
  '6,482',
  '37,438,974',
  '1,111,470',
  '33,684,208 ',
  'South America',
  '',
  '81541',
  '',
  '',
  '673',
  ''],
 ['36',
  'Switzerland',
  '4,382,359',
  '',
  '14,388                                ',
  '',
  '4,331,160',
  '+5,197',
  '36,811',
  '63',
  '499,492',
  '1,640',
  '23,292,004',
  '2,654,772',
  '8,773,637 ',
  'Europe',
  '',
  '26100',
  '',
  '',
  '4,196',
  ''],
 ['37',
  'Philippines',
  '4,067,170',
  '',
  '65,464                                ',
  '',
  '3,989,188',
  '',
  '12,518',
  '162',
  '36,150',
  '582',
  '34,073,949',
  '302,855',
  '112,508,994 ',
  'Asia',
  '',
  '281,7193',
  '',
  '',
  '111',
  ''],
 ['38',
  'South Africa',
  '4,050,050',
  '',
  '102,568                                ',
  '',
  '3,912,506',
  '',
  '34,976',
  '192',
  '66,661',
  '1,688',
  '26,473,049',
  '435,726',
  '60,756,135 ',
  'Africa',
  '',
  '155922',
  '',
  '',
  '576',
  ''],
 ['39',
  'Romania',
  '3,312,085',
  '',
  '67,408                                ',
  '',
  '3,237,640',
  '',
  '7,037',
  '110',
  '174,033',
  '3,542',
  '26,082,014',
  '1,370,477',
  '19,031,335 ',
  'Europe',
  '',
  '62821',
  '',
  '',
  '370',
  ''],
 ['40',
  'Denmark',
  '3,169,858',
  '',
  '7,889                                ',
  '',
  '3,154,368',
  '',
  '7,601',
  '17',
  '543,254',
  '1,352',
  '129,060,758',
  '22,118,571',
  '5,834,950 ',
  'Europe',
  '',
  '27400',
  '',
  '',
  '1,303',
  ''],
 ['41',
  'Hong Kong',
  '2,755,827',
  '',
  '12,276                                ',
  '',
  '2,126,102',
  '',
  '617,449',
  '54',
  '362,404',
  '1,614',
  '75,375,235',
  '9,912,187',
  '7,604,299 ',
  'Asia',
  '',
  '36190',
  '',
  '',
  '81,197',
  ''],
 ['42',
  'Sweden',
  '2,683,356',
  '',
  '22,110                                ',
  '',
  '2,619,890',
  '+1,628',
  '41,356',
  '43',
  '262,586',
  '2,164',
  '19,333,094',
  '1,891,883',
  '10,218,971 ',
  'Europe',
  '',
  '44621',
  '',
  '',
  '4,047',
  ''],
 ['43',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '21',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '',
  '171,6622',
  '',
  '',
  '16',
  ''],
 ['44',
  'Serbia',
  '2,452,493',
  '',
  '17,558                                ',
  '',
  '2,418,818',
  '',
  '16,117',
  '24',
  '283,426',
  '2,029',
  '11,925,792',
  '1,378,224',
  '8,653,016 ',
  'Europe',
  '',
  '44931',
  '',
  '',
  '1,863',
  ''],
 ['45',
  'Singapore',
  '2,207,670',
  '',
  '1,712                                ',
  '',
  '2,133,654',
  '',
  '72,304',
  '2',
  '371,440',
  '288',
  '24,755,451',
  '4,165,098',
  '5,943,546 ',
  'Asia',
  '',
  '33,4720',
  '',
  '',
  '12,165',
  ''],
 ['46',
  'Hungary',
  '2,188,737',
  '',
  '48,546                                ',
  '',
  '2,127,121',
  '',
  '13,070',
  '16',
  '227,845',
  '5,054',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '',
  '41981',
  '',
  '',
  '1,361',
  ''],
 ['47',
  'New Zealand',
  '2,117,094',
  '',
  '3,568                                ',
  '',
  '2,092,041',
  '',
  '21,485',
  '',
  '432,219',
  '728',
  '7,710,637',
  '1,574,177',
  '4,898,203 ',
  'Australia/Oceania',
  '',
  '21,3731',
  '',
  '',
  '4,386',
  ''],
 ['48',
  'Bangladesh',
  '2,037,250',
  '',
  '29,440                                ',
  '',
  '1,988,475',
  '',
  '19,335',
  '1,331',
  '12,135',
  '175',
  '15,160,408',
  '90,302',
  '167,885,689 ',
  'Asia',
  '',
  '825,70311',
  '',
  '',
  '115',
  ''],
 ['49',
  'Slovakia',
  '1,859,692',
  '+24',
  '20,845                                ',
  '+4',
  '1,837,846',
  '+31',
  '1,001',
  '28',
  '340,591',
  '3,818',
  '7,377,939',
  '1,351,223',
  '5,460,193 ',
  'Europe',
  '',
  '32621',
  '4',
  '0.7',
  '183',
  ''],
 ['50',
  'Georgia',
  '1,809,359',
  '',
  '16,899                                ',
  '',
  '1,776,548',
  '',
  '15,912',
  '',
  '455,903',
  '4,258',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '',
  '22350',
  '',
  '',
  '4,009',
  ''],
 ['51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '',
  '67291',
  '',
  '',
  '181',
  ''],
 ['52',
  'Ireland',
  '1,693,847',
  '',
  '8,339                                ',
  '',
  '1,674,770',
  '+251',
  '10,738',
  '36',
  '337,406',
  '1,661',
  '12,939,937',
  '2,577,575',
  '5,020,199 ',
  'Europe',
  '',
  '36020',
  '',
  '',
  '2,139',
  ''],
 ['53',
  'Pakistan',
  '1,575,953',
  '+18',
  '30,638                                ',
  '',
  '1,538,689',
  '',
  '6,626',
  '22',
  '6,867',
  '134',
  '30,570,862',
  '133,213',
  '229,488,994 ',
  'Asia',
  '',
  '1467,4908',
  '0.08',
  '',
  '29',
  ''],
 ['54',
  'Norway',
  '1,476,206',
  '',
  '4,571                                ',
  '',
  '1,468,933',
  '',
  '2,702',
  '20',
  '267,847',
  '829',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '',
  '41,2061',
  '',
  '',
  '490',
  ''],
 ['55',
  'Finland',
  '1,446,397',
  '',
  '8,263                                ',
  '',
  '1,421,408',
  '+1,580',
  '16,726',
  '21',
  '260,379',
  '1,487',
  '11,984,148',
  '2,157,378',
  '5,554,960 ',
  'Europe',
  '',
  '46720',
  '',
  '',
  '3,011',
  ''],
 ['56',
  'Kazakhstan',
  '1,404,104',
  '+169',
  '13,695                                ',
  '',
  '1,383,020',
  '',
  '7,389',
  '24',
  '73,111',
  '713',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '',
  '141,4022',
  '9',
  '',
  '385',
  ''],
 ['57',
  'Slovenia',
  '1,313,501',
  '',
  '7,025                                ',
  '',
  '1,292,579',
  '',
  '13,897',
  '21',
  '632,088',
  '3,381',
  '2,811,092',
  '1,352,765',
  '2,078,034 ',
  'Europe',
  '',
  '22961',
  '',
  '',
  '6,688',
  ''],
 ['58',
  'Bulgaria',
  '1,293,216',
  '',
  '38,122                                ',
  '',
  '1,251,048',
  '',
  '4,046',
  '40',
  '188,940',
  '5,570',
  '10,917,308',
  '1,595,026',
  '6,844,597 ',
  'Europe',
  '',
  '51801',
  '',
  '',
  '591',
  ''],
 ['59',
  'Lithuania',
  '1,290,919',
  '+27',
  '9,502                                ',
  '+1',
  '1,274,028',
  '+125',
  '7,389',
  '8',
  '484,996',
  '3,570',
  '10,324,083',
  '3,878,744',
  '2,661,708 ',
  'Europe',
  '',
  '22800',
  '10',
  '0.4',
  '2,776',
  ''],
 ['60',
  'Morocco',
  '1,271,868',
  '',
  '16,295                                ',
  '',
  '1,255,219',
  '',
  '354',
  '293',
  '33,672',
  '431',
  '12,876,656',
  '340,898',
  '37,772,756 ',
  'Africa',
  '',
  '302,3183',
  '',
  '',
  '9',
  ''],
 ['61',
  'Croatia',
  '1,265,333',
  '',
  '17,669                                ',
  '',
  '1,245,723',
  '',
  '1,941',
  '36',
  '311,713',
  '4,353',
  '5,437,406',
  '1,339,498',
  '4,059,286 ',
  'Europe',
  '',
  '32301',
  '',
  '',
  '478',
  ''],
 ['62',
  'Lebanon',
  '1,223,536',
  '',
  '10,752                                ',
  '',
  '1,087,587',
  '',
  '125,197',
  '74',
  '183,031',
  '1,608',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '',
  '56221',
  '',
  '',
  '18,728',
  ''],
 ['63',
  'Guatemala',
  '1,211,008',
  '',
  '20,017                                ',
  '',
  '1,174,756',
  '',
  '16,235',
  '5',
  '65,164',
  '1,077',
  '6,587,246',
  '354,457',
  '18,584,039 ',
  'North America',
  '',
  '159283',
  '',
  '',
  '874',
  ''],
 ['64',
  'Costa Rica',
  '1,171,802',
  '',
  '9,104                                ',
  '',
  '860,711',
  '',
  '301,987',
  '52',
  '226,114',
  '1,757',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '',
  '45691',
  '',
  '',
  '58,272',
  ''],
 ['65',
  'Bolivia',
  '1,168,711',
  '',
  '22,315                                ',
  '',
  '1,113,655',
  '',
  '32,741',
  '220',
  '97,452',
  '1,861',
  '2,705,422',
  '225,590',
  '11,992,656 ',
  'South America',
  '',
  '105374',
  '',
  '',
  '2,730',
  ''],
 ['66',
  'Tunisia',
  '1,147,645',
  '',
  '29,285                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '44',
  '95,267',
  '2,431',
  '4,985,258',
  '413,829',
  '12,046,656 ',
  'Africa',
  '',
  '104112',
  '',
  '',
  '694',
  ''],
 ['67',
  'Cuba',
  '1,112,134',
  '',
  '8,530                                ',
  '',
  '1,103,455',
  '',
  '149',
  '23',
  '98,370',
  '754',
  '14,276,770',
  '1,262,799',
  '11,305,652 ',
  'North America',
  '',
  '101,3251',
  '',
  '',
  '13',
  ''],
 ['68',
  'UAE',
  '1,047,371',
  '',
  '2,348                                ',
  '',
  '1,030,367',
  '',
  '14,656',
  '',
  '103,887',
  '233',
  '198,071,556',
  '19,646,477',
  '10,081,785 ',
  'Asia',
  '',
  '104,2940',
  '',
  '',
  '1,454',
  ''],
 ['69',
  'Ecuador',
  '1,040,463',
  '',
  '35,940                                ',
  '',
  '1,000,080',
  '+1,110',
  '4,443',
  '759',
  '57,442',
  '1,984',
  '3,082,403',
  '170,173',
  '18,113,361 ',
  'South America',
  '',
  '175046',
  '',
  '',
  '245',
  ''],
 ['70',
  'Panama',
  '1,025,844',
  '',
  '8,575                                ',
  '',
  '1,014,270',
  '',
  '2,999',
  '16',
  '230,684',
  '1,928',
  '7,404,783',
  '1,665,132',
  '4,446,964 ',
  'North America',
  '',
  '45191',
  '',
  '',
  '674',
  ''],
 ['71',
  'Uruguay',
  '1,020,161',
  '',
  '7,570                                ',
  '',
  '1,004,306',
  '',
  '8,285',
  '18',
  '291,807',
  '2,165',
  '6,114,822',
  '1,749,083',
  '3,496,016 ',
  'South America',
  '',
  '34621',
  '',
  '',
  '2,370',
  ''],
 ['72',
  'Mongolia',
  '1,007,765',
  '',
  '2,179                                ',
  '',
  '1,005,087',
  '',
  '499',
  '192',
  '298,325',
  '645',
  '4,030,048',
  '1,193,000',
  '3,378,078 ',
  'Asia',
  '',
  '31,5501',
  '',
  '',
  '148',
  ''],
 ['73',
  'Nepal',
  '1,001,020',
  '',
  '12,020                                ',
  '',
  '988,979',
  '',
  '21',
  '',
  '33,118',
  '398',
  '5,992,656',
  '198,264',
  '30,225,582 ',
  'Asia',
  '',
  '302,5155',
  '',
  '',
  '0.7',
  ''],
 ['74',
  'Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592',
  '',
  '1,327',
  '',
  '105,381',
  '755',

In [17]:
import csv
file = open('covid.csv',"w")
x = csv.writer(file)
x.writerows(list_data)
file.close()

In [19]:
pwd

'C:\\Users\\user\\Desktop\\python basic'

In [20]:
import pandas as pd
df = pd.read_csv('covid.csv')
df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 122: invalid start byte